env:
  CIRRUS_CLONE_DEPTH: 1

windows_task:
  name: "Windows"
  alias: cocaine_diesel_windows
  windows_container:
    image: cirrusci/windowsservercore:visualstudio2022
    cpu: 8
    memory: 8G
  script:
    - "\"C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Auxiliary\\Build\\vcvarsall.bat\" amd64"
    - ggbuild\lua.exe make.lua release > build.ninja
    - ggbuild\ninja.exe -v -k 0
    - ggbuild\lua.exe ggbuild\ninja_timeline.lua
    - ggbuild\ducible.exe release\client.exe
    - ggbuild\ducible.exe release\server.exe
    - ggbuild\ducible.exe release\bc4.exe
    - ggbuild\ducible.exe release\dieselmap.exe
  cocaine_diesel_windows_artifacts:
    path: "release/*"

macos_task:
  name: "macOS"
  macos_instance:
    image: ghcr.io/cirruslabs/macos-sonoma-xcode:latest
  env:
    ZERO_AR_DATE: "1"
  script:
    - ggbuild/lua.macos make.lua release > build.ninja
    - ggbuild/ninja.macos -v -k 0
    - ggbuild/lua.macos ggbuild/ninja_timeline.lua
  cocaine_diesel_macos_artifacts:
    path: "release/*"

linux_task:
  name: "Linux"
  alias: cocaine_diesel_linux
  container:
    image: alpine
    cpu: 8
    memory: 4G
  install_script:
    - apk add bash git curl wget
  build_script:
    - ggbuild/lua.linux make.lua release > build.ninja
    - ggbuild/ninja.linux -v -k 0
    - ggbuild/lua.linux ggbuild/ninja_timeline.lua
    - ls release
  test_script:
    - tests/test_downloads.sh
  cocaine_diesel_linux_artifacts:
    path: "release/*"
