windows_task:
  name: "Windows"
  windows_container:
    image: cirrusci/windowsservercore:visualstudio2022
    cpu: 2
    memory: 2G
  script:
    - call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Auxiliary\\Build\\vcvarsall.bat" amd64
    - ggbuild\lua.exe make.lua release > build.ninja
    - ggbuild\ninja.exe -v -k 0
    - ggbuild\lua.exe ggbuild\ninja_timeline.lua
    - ggbuild\ducible.exe release\client.exe
    - ggbuild\ducible.exe release\server.exe
    - ggbuild\ducible.exe release\bc4.exe
    - ggbuild\ducible.exe release\dieselmap.exe

macos_task:
  name: "macOS"
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  script:
    - echo hi

linux_task:
  name: "Linux"
  container:
    image: alpine
    cpu: 4
    memory: 2G
  script:
    - apk add bash git wget
    - ggbuild/lua.linux make.lua release > build.ninja
    - ggbuild/ninja.linux -v -k 0
    - ggbuild/lua.linux ggbuild/ninja_timeline.lua
