version: "{build}"
clone_depth: 1
image: Ubuntu

build_script:
- sh: ggbuild/lua.linux make.lua release > build.ninja
- sh: ggbuild/ninja.linux -v -k 0
- sh: ggbuild/lua.linux ggbuild/ninja_timeline.lua

test_script:
- sh: tests/test_downloads.sh
- sh: tests/test_entities_ent_are_the_same.sh

artifacts:
- path: release
  name: cocaine_diesel_linux
