lib( "meshoptimizer", {
	"libs/meshoptimizer/allocator.cpp",
	"libs/meshoptimizer/clusterizer.cpp",
	"libs/meshoptimizer/indexcodec.cpp",
	"libs/meshoptimizer/indexgenerator.cpp",
	"libs/meshoptimizer/overdrawanalyzer.cpp",
	"libs/meshoptimizer/overdrawoptimizer.cpp",
	"libs/meshoptimizer/simplifier.cpp",
	"libs/meshoptimizer/spatialorder.cpp",
	"libs/meshoptimizer/stripifier.cpp",
	"libs/meshoptimizer/vcacheanalyzer.cpp",
	"libs/meshoptimizer/vcacheoptimizer.cpp",
	"libs/meshoptimizer/vertexcodec.cpp",
	"libs/meshoptimizer/vertexfilter.cpp",
	"libs/meshoptimizer/vfetchanalyzer.cpp",
	"libs/meshoptimizer/vfetchoptimizer.cpp",
} )
