# env/cssky/cube_up.tga
# env/cssky/cube_dn.tga
# env/cssky/cube_lf.tga
# env/cssky/cube_ft.tga
# env/cssky/cube_rt.tga
# env/cssky/cube_bk.tga
rm env/wtest15a_px.tga
rm env/cellbright_py.tga
rm env/chrome/02_px.jpg
rm env/chrome/02_nx.jpg
rm env/chrome/02_ny.jpg
rm env/chrome/02_py.jpg
rm env/chrome/02_nz.jpg
rm env/chrome/02_pz.jpg
rm env/36sky_up.ktx
rm env/znsky_nz.tga
rm env/wtest15a_nz.tga
rm env/celldouble_nx.tga
rm env/znsky_ny.tga
rm env/city1blue_bk.ktx
rm env/starsky.ktx
rm env/televoid/void_env.ktx
rm env/televoid/void.ktx
rm env/znsky_px.tga
rm env/city1blue_rt.ktx
rm env/celllight_pz.tga
rm env/cellbright_nz.tga
rm env/city1blue_dn.ktx
rm env/znsky_py.tga
rm env/nightredsky.ktx
rm env/cellbright_px.tga
rm env/celllight_py.tga
rm env/celldouble_pz.tga
rm env/celllight_nx.tga
rm env/city1blue_lf.ktx
rm env/city1_lf.ktx
rm env/wdm1env_px.jpg
rm env/wtest15a_py.tga
rm env/wdm1env_py.jpg
rm env/celldouble_nz.tga
rm env/starsky_up.ktx
rm env/wdm1env_nx.jpg
rm env/cell_pz.tga
rm env/wdm1env_nz.jpg
rm env/nightredsky_up.ktx
rm env/city1_ft.ktx
rm env/wamphi3.ktx
rm env/cell_ny.tga
rm env/celldouble_ny.tga
rm env/znsky_pz.tga
rm env/nightsky.ktx
rm env/city1blue_ft.ktx
rm env/znsky_nx.tga
rm env/cellbright_nx.tga
rm env/wtest15a_ny.tga
rm env/celldouble_px.tga
rm env/celllight_px.tga
rm env/celllight_ny.tga
rm env/celllight_nz.tga
rm env/36sky.ktx
rm env/cellbright_ny.tga
rm env/city1blue_up.ktx
rm env/cell_nz.tga
rm env/cell_nx.tga
rm env/wtest15a_nx.tga
rm env/city1_up.ktx
rm env/wdm1env_pz.jpg
rm env/cellbright_pz.tga
rm env/wtest15a_pz.tga
rm env/cell_py.tga
rm env/nightsky_up.ktx
rm env/wdm1env_ny.jpg
rm env/cell_px.tga
# env/2d/chrome1.tga
rm env/2d/map1.tga
rm env/celldouble_py.tga
rm env/city1_rt.ktx
rm env/city1_dn.ktx
rm env/city1_bk.ktx
rm textures/glass/melee.ktx
rm textures/blxbis/blx_panel_masked_norm.tga
rm textures/blxbis/grate_norm.tga
rm textures/blxbis/trim3_turq.jpg
rm textures/blxbis/wall_turq_dark_norm.tga
rm textures/blxbis/blx_panel_masked_gloss.tga
rm textures/blxbis/ratowerskin1_spot.tga
rm textures/blxbis/wallgreystripes_circuits_512_norm.tga
rm textures/blxbis/towerskin2_norm.tga
rm textures/blxbis/wall1_turq.jpg
rm textures/blxbis/trim5_turq.jpg
rm textures/blxbis/trim5_turq_norm.tga
rm textures/blxbis/wallgreystripes_512.ktx
rm textures/blxbis/blxbis_light_h.jpg
rm textures/blxbis/trim6_turq.jpg
rm textures/blxbis/blx_dark_ws_norm.tga
rm textures/blxbis/trim3corner_turq.jpg
rm textures/blxbis/trim1_turq_gloss.tga
rm textures/blxbis/aluminium_gloss.tga
rm textures/blxbis/grate.tga
rm textures/blxbis/trim6_turq_gloss.tga
rm textures/blxbis/trim1_turq_norm.tga
rm textures/blxbis/wall3grey_512.ktx
rm textures/blxbis/scratches0002_tiled.ktx
rm textures/blxbis/trim1_turq.jpg
rm textures/blxbis/wallgreystripes_circuitsblend_512.tga
rm textures/blxbis/wall_turq_dark_stripes_gloss.tga
rm textures/blxbis/wallgrey_512.ktx
rm textures/blxbis/wall4_turq_gloss.tga
rm textures/blxbis/light_turq2.tga
rm textures/blxbis/trim_06_gloss.tga
rm textures/blxbis/spotweap_alphablend.tga
rm textures/blxbis/wall_turq_dark.jpg
rm textures/blxbis/wallgreystripes_512_norm.tga
rm textures/blxbis/wall_turq_dark_stripes.jpg
rm textures/blxbis/blx_spacer_alpha.jpg
rm textures/blxbis/aluminium_norm.tga
rm textures/blxbis/trim_5_gloss.tga
rm textures/blxbis/ratowerskin1_spot_gloss.tga
rm textures/blxbis/wall5_turq_norm.tga
rm textures/blxbis/trim3corner_turq_gloss.tga
rm textures/blxbis/wall4_turq.jpg
rm textures/blxbis/ground.ktx
# textures/blxbis/ice_02.ktx
rm textures/blxbis/light_turq_norm.tga
rm textures/blxbis/trim_5_blend.tga
rm textures/blxbis/blx_dark_ws.ktx
rm textures/blxbis/wall_turq_dark_stripes_norm.tga
rm textures/blxbis/blx_panel_masked.tga
rm textures/blxbis/metal_coldgreylight_256_norm.tga
rm textures/blxbis/scratches0002_tiled_gloss.tga
# textures/blxbis/aluminium.tga
rm textures/blxbis/wall_turq_dark_gloss.tga
rm textures/blxbis/trim3_turq_gloss.tga
rm textures/blxbis/iceline.ktx
rm textures/blxbis/towerskin2_gloss.tga
rm textures/blxbis/trim2_turq.jpg
rm textures/blxbis/step.jpg
rm textures/blxbis/spotweap_shape2.tga
rm textures/blxbis/glass.tga
rm textures/blxbis/wall5_turq_gloss.tga
rm textures/blxbis/ground_norm.tga
rm textures/blxbis/wallgrey_512_norm.tga
rm textures/blxbis/trim_06_blend.tga
rm textures/blxbis/wall1_turq_norm.tga
rm textures/blxbis/light_turq_gloss.tga
# textures/blxbis/ice_01_alpha.tga
rm textures/blxbis/light_turq_blend.tga
rm textures/blxbis/trim_4_turq_blend.tga
rm textures/blxbis/wall5_turq.jpg
rm textures/blxbis/light_turq2_gloss.tga
rm textures/blxbis/blx_spacer.ktx
rm textures/blxbis/metal_coldgreylight_256.ktx
rm textures/blxbis/trim_06.tga
rm textures/blxbis/ratowerskin1_spot_norm.tga
rm textures/blxbis/trim3_turq_norm.tga
rm textures/blxbis/trim4_turq.jpg
rm textures/blxbis/towerskin1_norm.tga
# textures/blxbis/skyturq_scroll.ktx
rm textures/blxbis/metal_coldgreylight_256_gloss.tga
rm textures/blxbis/towerskin1_gloss.tga
rm textures/blxbis/wall1_turq_gloss.tga
rm textures/blxbis/trim3corner_turq_norm.tga
rm textures/blxbis/step_add.jpg
rm textures/blxbis/trim2_turq_gloss.tga
rm textures/blxbis/wallblock.jpg
rm textures/blxbis/scratches0002_tiled_norm.tga
rm textures/blxbis/towerskin2.tga
rm textures/blxbis/wallgreystripes_circuits_512.ktx
rm textures/blxbis/light_turq2_norm.tga
# textures/blxbis/skyturq_scroll2.ktx
rm textures/blxbis/wall4_turq_norm.tga
rm textures/blxbis/trim6_turq_norm.tga
# textures/blxbis/sh/circuits_surface_512.ktx
# textures/blxbis/sh/circuits_surface_512_norm.tga
rm textures/blxbis/sh/circuits_blue_512_gloss.tga
# textures/blxbis/sh/circuits_blue_512.tga
rm textures/blxbis/light_turq2_blend.tga
rm textures/blxbis/wall3grey_512_blend.tga
rm textures/blxbis/trim_06_norm.tga
rm textures/blxbis/wallblock_norm.tga
# textures/blxbis/ice_01.ktx
rm textures/blxbis/wallpanel_grey1.ktx
# textures/blxbis/glass_lined.tga
rm textures/blxbis/trim5_turq_gloss.tga
rm textures/blxbis/light_turq.tga
rm textures/blxbis/blx_dark_ws_gloss.tga
rm textures/blxbis/towerskin1.ktx
rm textures/blxbis/trim_5_norm.tga
rm textures/blxbis/trim_5.tga
rm textures/blxbis/trim2_turq_norm.tga
rm textures/refly_metal/36histexturehewantedsobad_norm.tga
rm textures/refly_metal/metal17_norm.tga
rm textures/refly_metal/metal17_gloss.tga
rm textures/refly_metal/36histexturehewantedsobad_gloss.tga
rm textures/refly_metal/metal17.tga
rm textures/refly_metal/36histexturehewantedsobad.tga
rm textures/noir/thisway01.tga
rm textures/noir/thisway03.tga
rm textures/noir/natsbar03.tga
rm textures/noir/natsbar01.tga
rm textures/noir/thisway02.tga
rm textures/noir/window.tga
rm textures/noir/natsbar02.tga
rm textures/noir/window4_gloss.tga
rm textures/noir/badabing.tga
rm textures/noir/window4_norm.tga
rm textures/noir/natsbar04.tga
rm textures/noir/window4.tga
# textures/concrete/concrete2.tga
rm textures/concrete/baseblue0060.ktx
rm textures/concrete/concretebunker0068_norm.tga
# textures/concrete/stucco01_norm.tga
# textures/concrete/concretecold01.ktx
# textures/concrete/concreteredandwhite.ktx
# textures/concrete/concretecleanstriped.ktx
rm textures/concrete/concretegreyandwhite.ktx
rm textures/concrete/stucco01.ktx
# textures/concrete/concreteclean_norm.tga
rm textures/concrete/blueplaster_norm.tga
rm textures/concrete/concrete2_gloss.tga
# textures/concrete/stucco01b.ktx
# textures/concrete/concretecold01_norm.tga
rm textures/concrete/concretebunker0068.tga
# textures/concrete/stucco01c.ktx
# textures/concrete/blueplaster.ktx
rm textures/concrete/concrete2_norm.tga
# textures/concrete/concretegreyandred.ktx
rm textures/concrete/basered0081_norm.tga
rm textures/concrete/concreteclean.ktx
rm textures/concrete/baseblue0060_norm.tga
rm textures/concrete/basered0081.ktx
# textures/concrete/concretecold02.tga
rm textures/concrete/stucco01e.ktx
rm textures/concrete/concretegrey.ktx
# textures/concrete/concretegrey_norm.tga
rm textures/concrete/concretered.ktx
rm textures/blx/blx_md_lt_norm.tga
rm textures/blx/blx_tile_alpha.tga
rm textures/blx/blx_tile.tga
rm textures/blx/blx_light_gridded_r.tga
rm textures/blx/blx_light_h.tga
rm textures/blx/blx_white_stripe.jpg
rm textures/blx/blx_wall_2.tga
rm textures/blx/blx_wall_7_norm.tga
rm textures/blx/blx_tile_gloss.tga
rm textures/blx/blx_plane_dk_gloss.tga
rm textures/blx/blx_wall_1_norm.tga
rm textures/blx/blx_glow2.jpg
rm textures/blx/blx_lava2.tga
rm textures/blx/blx_display_1.tga
rm textures/blx/blx_grid_gloss.tga
rm textures/blx/blx_md_lt_alpha.tga
rm textures/blx/blx_dark.tga
rm textures/blx/blx_dark_ws_norm.tga
rm textures/blx/blx_light_blue.jpg
rm textures/blx/blx_neon_q.tga
rm textures/blx/blx_md_lt_gloss.tga
rm textures/blx/blx_wall_1.tga
rm textures/blx/blx_white_edge1.tga
rm textures/blx/blx_circle.tga
rm textures/blx/blx_ecel_bounce_blend.tga
rm textures/blx/stream.tga
rm textures/blx/blx_wall_2a.tga
rm textures/blx/blx_spacer.tga
rm textures/blx/blx_wall_1a_norm.tga
rm textures/blx/copy of blx_plane_md_gloss.tga
rm textures/blx/blx_circle_gloss.tga
rm textures/blx/blx_wall_alpha.tga
rm textures/blx/blx_wall_2_gloss.tga
rm textures/blx/blx_wall_4_norm.tga
rm textures/blx/blx_plane_lt_gloss.tga
rm textures/blx/blx_wall_5_alpha.tga
rm textures/blx/blx_wall_7_alpha.tga
rm textures/blx/blx_wall_1_alpha.tga
rm textures/blx/blx_wall_5.tga
rm textures/blx/circuits_red_512.tga
rm textures/blx/blx_md_lt_B.tga
rm textures/blx/blx_circle_norm.tga
rm textures/blx/blx_wall_2b_gloss.tga
rm textures/blx/blx_md_lt.tga
rm textures/blx/blx_ecel_bounce.tga
rm textures/blx/blx_plane_md_gloss.tga
rm textures/blx/blx_tile_norm.tga
# textures/blx/new_sky.tga
rm textures/blx/blx_grid_norm.tga
rm textures/blx/blx_wall_2b_norm.tga
rm textures/blx/blx_wall_2a_norm.tga
rm textures/blx/blx_grid_alpha.tga
rm textures/blx/blx_md_lt_B_norm.tga
rm textures/blx/blx_wall_1a_gloss.tga
rm textures/blx/blx_wall_7.tga
rm textures/blx/blx_ultrabright.tga
rm textures/blx/blx_dec.tga
rm textures/blx/blx_dark_ws.tga
rm textures/blx/blx_spacer_2.tga
rm textures/blx/blx_white_edge.tga
rm textures/blx/blx_wall_1_gloss.tga
rm textures/blx/blx_wall_2a_alpha.tga
rm textures/blx/blx_wall_7_gloss.tga
rm textures/blx/blx_wall_3.tga
rm textures/blx/blx_wall_1a.jpg
rm textures/blx/blx_md_lt_B_alpha.tga
rm textures/blx/blx_wall_4.tga
rm textures/blx/blx_ultrabright_blue.tga
rm textures/blx/blx_wall_3_norm.tga
rm textures/blx/blx_white_stripe1.jpg
rm textures/blx/blx_plane_lt.tga
rm textures/blx/blx_wall_3_alpha.tga
rm textures/blx/warsow_neon.tga
rm textures/blx/blx_white_line.tga
rm textures/blx/blx_md_lt_B_gloss.tga
rm textures/blx/blx_grid.tga
rm textures/blx/blx_wall_2_norm.tga
rm textures/blx/blx_floor_1.tga
rm textures/blx/circuits_surface_512.tga
rm textures/blx/blx_tech_1.tga
rm textures/blx/blx_plane_md.tga
rm textures/blx/blx_white_square.tga
rm textures/blx/blx_ecel_bounce_alpha.tga
rm textures/blx/blx_wall_alpha_a.tga
rm textures/blx/blx_wall_3_gloss.tga
rm textures/blx/blx_plane_dk.tga
rm textures/blx/blx_floor_1_norm.tga
rm textures/blx/blx_wall_1a.tga
rm textures/blx/circuits_white_512.tga
rm textures/blx/blx_spacer_alpha.tga
rm textures/blx/blx_wall_6.tga
rm textures/blx/blx_wall_2_alpha.tga
rm textures/blx/blx_wall_2a_gloss.tga
rm textures/blx/bLx_ecel_bounce_small.jpg
rm textures/blx/blx_wall_2b.tga
rm textures/blx/blx_light_gridded.tga
rm textures/blx/blx_floor_1_alpha.tga
rm textures/blx/blx_glow2b.jpg
rm textures/blx/blx_floor_1_gloss.tga
rm textures/blx/blx_wall_5_norm.tga
rm textures/blx/blx_wall_5_gloss.tga
rm textures/blx/blx_glow.jpg
rm textures/blx/circuits_blue_512.tga
rm textures/blx/blx_dark_ws_gloss.tga
rm textures/blx/blx_light_rh.tga
rm textures/cha0s_ctf/cement_2_flat_grey.tga
rm textures/russus/transscreen_alpha.tga
rm textures/russus/spray_alpha.tga
rm textures/russus/cement-tiled_grey_norm.jpg
rm textures/russus/spray_beta.tga
rm textures/russus/cement-tiled_grey_gloss.tga
rm textures/russus/cement-tiled_grey.tga
rm textures/russus/transscreen_beta.tga
rm textures/36_lights/light-FFFFFF.tga
# textures/grates/fence01.tga
rm textures/grates/fence02.tga
rm textures/grates/fence03.tga
rm textures/grates/fence01_gloss.tga
# textures/grates/simplegrid.ktx
# textures/grates/grid02.tga
rm textures/grates/grid02_norm.tga
# textures/grates/fence01_norm.tga
rm textures/grates/simplegrid_norm.ktx
rm textures/dispenser/ammotex1.jpg
rm textures/dispenser/ammotex2.jpg
rm textures/refly_tiles/zadaztiles.tga
rm textures/tutorial/questionmark_1.tga
rm textures/tutorial/strjump_right.ktx
rm textures/tutorial/jump_sprite.ktx
rm textures/tutorial/walljump_sprite.ktx
rm textures/tutorial/strjump_left.ktx
rm textures/refly_bricks/bricksdark1_norm.tga
rm textures/refly_bricks/bricks1_norm.tga
rm textures/refly_bricks/bricks4_norm.tga
rm textures/refly_bricks/bricks1.tga
rm textures/refly_bricks/Bricks_Refly_DarkGrey1_norm.tga
rm textures/refly_bricks/bricks2_norm.tga
rm textures/refly_bricks/bricks2.tga
rm textures/refly_bricks/bricksdark1org_norm.tga
rm textures/refly_bricks/bricks4.tga
rm textures/refly_bricks/bricksdark1org.tga
rm textures/refly_bricks/Bricks_Refly_DarkGrey1.tga
rm textures/refly_bricks/bricksdark1.tga
rm textures/billboard/c6.jpg
# textures/billboard/terebi_05.jpg
rm textures/billboard/bigbill5.ktx
rm textures/billboard/small4.tga
# textures/billboard/terebi_03.jpg
# textures/billboard/bigbill1.ktx
rm textures/billboard/c2.jpg
rm textures/billboard/bulletspurple.jpg
rm textures/billboard/ver1.tga
# textures/billboard/terebi_06.jpg
# textures/billboard/scanlinenoise.tga
rm textures/billboard/ver2.tga
rm textures/billboard/neon1.tga
rm textures/billboard/bulletsorange.jpg
rm textures/billboard/bulletsblue.jpg
rm textures/billboard/bigver1.tga
# textures/billboard/terebi_07.jpg
rm textures/billboard/introvid.jpg
rm textures/billboard/bulletsblue2.jpg
rm textures/billboard/c1.jpg
# textures/billboard/small1.tga
rm textures/billboard/bullets.jpg
# textures/billboard/terebi_01.jpg
# textures/billboard/terebi_04.jpg
rm textures/billboard/c4.jpg
rm textures/billboard/terebi.jpg
rm textures/billboard/c3.jpg
rm textures/billboard/bigbill6.ktx
# textures/billboard/small3.tga
rm textures/billboard/PorkyPie.tga
# textures/billboard/terebi_02.jpg
rm textures/billboard/c5.jpg
rm textures/billboard/bulletsblue3.jpg
# textures/billboard/small2.tga
# textures/billboard/code.jpg
rm textures/billboard/bigbill2.ktx
# textures/billboard/bigbill9.tga
rm textures/billboard/ver3.tga
rm textures/wdm6/kimza_crocinus_pillar2_norm.tga
rm textures/wdm6/kimza_wt3_pillar3_orange_norm.tga
rm textures/wdm6/kimza_crocinus_pillar2.tga
rm textures/wdm6/kimza_wt3_pillar3_orange.tga
rm textures/HazelH/rivet_trim2_norm.tga
rm textures/HazelH/sky_colour.tga
rm textures/HazelH/verticalborder_whitelight_bright.tga
rm textures/HazelH/verticalborder_orangelight_bright.tga
rm textures/HazelH/lightstrip_transparent.tga
rm textures/HazelH/base_dblue.tga
rm textures/HazelH/verticalborder_whitelight.tga
rm textures/HazelH/verticalborder2_whitelight2.tga
rm textures/HazelH/glow_orange.tga
rm textures/HazelH/base_midblue.tga
rm textures/HazelH/wallborder_orangelight_bright.tga
rm textures/HazelH/wallborder_whitelight.tga
rm textures/HazelH/verticalborder_orangelight.tga
rm textures/HazelH/wallborder.tga
rm textures/HazelH/grate.tga
rm textures/HazelH/lightstrip.tga
rm textures/HazelH/wallpanels_norm.tga
rm textures/HazelH/floorpanels.tga
rm textures/HazelH/wallborder_orangelight.tga
rm textures/HazelH/flat/sky_colour.tga
rm textures/HazelH/flat/verticalborder_whitelight.tga
rm textures/HazelH/flat/wallborder_whitelight.tga
rm textures/HazelH/flat/verticalborder_orangelight.tga
rm textures/HazelH/flat/wallborder.tga
rm textures/HazelH/flat/floorpanels.tga
rm textures/HazelH/flat/wallborder_orangelight.tga
rm textures/HazelH/flat/verticalborder2_whitelight.tga
rm textures/HazelH/flat/wallpanels.tga
rm textures/HazelH/flat/verticalborder.tga
rm textures/HazelH/flat/ventpanel2.tga
rm textures/HazelH/flat/wallpanels2.tga
rm textures/HazelH/flat/rivet_trim2.tga
rm textures/HazelH/flat/floortiles.tga
rm textures/HazelH/flat/sky_planet.tga
rm textures/HazelH/flat/verticalborder2_orangelight.tga
rm textures/HazelH/flat/ventpanel1.tga
rm textures/HazelH/flat/ventpanel3.tga
rm textures/HazelH/flat/wallpanels_dark.tga
rm textures/HazelH/solidcolour_lightgrey.tga
rm textures/HazelH/verticalborder2_whitelight.tga
rm textures/HazelH/wallpanels.tga
rm textures/HazelH/verticalborder_gloss.tga
rm textures/HazelH/verticalborder_norm.tga
rm textures/HazelH/wallborder_whitelight_bright.tga
rm textures/HazelH/wallborder_gloss.tga
rm textures/HazelH/floorpanels_norm.tga
rm textures/HazelH/verticalborder.tga
rm textures/HazelH/base_lightgrey.tga
rm textures/HazelH/wallpanels_gloss.tga
rm textures/HazelH/verticalborder2_orangelight_bright.tga
rm textures/HazelH/rivet_trim_norm.tga
rm textures/HazelH/ventpanel2.tga
rm textures/HazelH/glow_orange_circle.tga
rm textures/HazelH/wallpanels2.tga
rm textures/HazelH/solidcolour_white.tga
rm textures/HazelH/verticalborder2.tga
rm textures/HazelH/solidcolour_dblue.tga
rm textures/HazelH/rivet_trim2.tga
rm textures/HazelH/floortiles_mid.tga
rm textures/HazelH/floortiles_mid_norm.tga
rm textures/HazelH/base_dblue2.tga
rm textures/HazelH/floortiles_gloss.tga
rm textures/HazelH/ventpanel2_gloss.tga
rm textures/HazelH/floortiles.tga
rm textures/HazelH/floortiles_norm.tga
rm textures/HazelH/ventpanel1_gloss.tga
rm textures/HazelH/solidcolour_midblue.tga
rm textures/HazelH/ventpanel1_norm.tga
rm textures/HazelH/floortiles_mid_gloss.tga
rm textures/HazelH/wallborder_norm.tga
rm textures/HazelH/verticalborder_lights_norm.tga
rm textures/HazelH/solidcolour_dblue2.tga
rm textures/HazelH/ventpanel3_norm.tga
rm textures/HazelH/sky_planet.tga
rm textures/HazelH/wallpanels2_norm.tga
rm textures/HazelH/ventpanel3_gloss.tga
rm textures/HazelH/floorpanels_dudv.tga
rm textures/HazelH/verticalborder2_orangelight.tga
rm textures/HazelH/floorpanels_gloss.tga
rm textures/HazelH/wallborder_light_norm.tga
rm textures/HazelH/rivet_trim.tga
rm textures/HazelH/puddle.tga
rm textures/HazelH/verticalborder2_whitelight_bright.tga
rm textures/HazelH/ventpanel2_norm.tga
rm textures/HazelH/base_white.tga
rm textures/HazelH/ventpanel1.tga
rm textures/HazelH/ventpanel3.tga
rm textures/HazelH/wallpanels_dark.tga
rm textures/refly_wood/wood2.tga
rm textures/refly_wood/wood1.tga
rm textures/refly_wood/wood1_norm.tga
rm textures/refly_wood/wood3_norm.tga
rm textures/refly_wood/wood2_norm.tga
rm textures/refly_wood/wood3.tga
rm textures/tiles/floor_tiled_norm.tga
rm textures/tiles/floorsregular0100.ktx
rm textures/tiles/floorsregular0100yellow_gloss.tga
rm textures/tiles/floor_tiled.tga
rm textures/tiles/floorsregular0100_norm.tga
rm textures/tiles/floor_gloss.tga
rm textures/tiles/floor_norm.tga
rm textures/tiles/floorsregular0100_gloss.tga
rm textures/tiles/floorsregular0100grey_norm.tga
rm textures/tiles/floorsregular0100yellow.ktx
rm textures/tiles/floor.tga
rm textures/tiles/floorsregular0100grey_gloss.tga
rm textures/tiles/floorsregular0100grey.ktx
rm textures/refly_crates/36dm2crate_gloss.tga
rm textures/refly_crates/36dm2crate_norm.tga
rm textures/refly_crates/36dm2crateinside_gloss.tga
rm textures/refly_crates/36dm2crate.tga
rm textures/refly_crates/36dm2crateinside.tga
rm textures/plastic/green.tga
# textures/plastic/pvc_grey.tga
# textures/plastic/grey50_gloss.tga
# textures/plastic/grey65.tga
# textures/plastic/grey85_gloss.tga
rm textures/plastic/blue.tga
# textures/plastic/grey50.tga
# textures/plastic/grey35.tga
# textures/plastic/grey75_gloss.tga
# textures/plastic/pvc_grey_gloss.tga
# textures/plastic/red.tga
# textures/plastic/grey35_gloss.tga
rm textures/plastic/red2.tga
# textures/plastic/grey75.tga
# textures/plastic/grey65_gloss.tga
# textures/plastic/grey85.tga
rm textures/format/teleglow_purple.tga
rm textures/format/glow_baby.tga
rm textures/format/lightstrip_red.tga
rm textures/format/glow_blue.tga
rm textures/format/glow_red.tga
rm textures/format/lightstrip_blue.tga
rm textures/format/teleglow_green.tga
rm textures/format/glow_purple.tga
rm textures/format/lightstrip_yellow.tga
rm textures/format/sign_jump_pad.tga
rm textures/format/lightstrip_green.tga
rm textures/format/jump_pad_ring.tga
rm textures/format/lightstrip_purple.tga
rm textures/format/lightstrip_baby.tga
rm textures/format/teleglow_yellow.tga
rm textures/format/teleglow_red.tga
rm textures/format/lightstrip_orange.tga
rm textures/format/glow_green.tga
rm textures/format/glow_yellow.tga
rm textures/null.tga
rm textures/flatnorm.tga
rm textures/trees/barkdecidious048_gloss.tga
rm textures/trees/barkdecidious048.tga
rm textures/trees/barkdecidious048_norm.tga
rm textures/solidfake_lights/lights_grid_orange_1s.tga
rm textures/solidfake_lights/lights_line_orange_1_black.tga
rm textures/solidfake_lights/lights_line_orange_1s.tga
rm textures/solidfake_lights/lights_line_orange_1s_black.tga
rm textures/solidfake_lights/lights_grid_orange_1s_black.tga
rm textures/solidfake_lights/lights_line_orange_1.tga
rm textures/concrete_techwalls/concreteclean_blx_wall5_norm.tga
rm textures/concrete_techwalls/concreteclean_blx_wall2.tga
rm textures/concrete_techwalls/concreteclean_blx_wall1_norm.tga
rm textures/concrete_techwalls/oldplaster_blx_wall2b.tga
rm textures/concrete_techwalls/oldplaster_blx_wall2b_norm.tga
rm textures/concrete_techwalls/concrete_blx_tile.tga
rm textures/concrete_techwalls/concreteclean_blx_wall1.tga
rm textures/concrete_techwalls/concreteclean_norm.tga
rm textures/concrete_techwalls/concreteclean_blx_wall5.tga
rm textures/concrete_techwalls/concrete_blx_tile_norm.tga
rm textures/concrete_techwalls/concreteclean_blx_wall2_norm.tga
rm textures/concrete_techwalls/concreteclean.tga
rm textures/wsw_cave1/ball_mask.ktx
rm textures/wsw_cave1/ball_mask1.tga
rm textures/wsw_cave1/water_flow_gloss.ktx
rm textures/wsw_cave1/scratchedmetal2_norm.tga
rm textures/wsw_cave1/water_flow.tga
rm textures/wsw_cave1/ball_glowb_portal.tga
rm textures/wsw_cave1/ball_dudv.tga
# textures/wsw_cave1/ball_glowb.tga
rm textures/wsw_cave1/ball_norm.tga
rm textures/wsw_cave1/ball_blend.ktx
rm textures/wsw_cave1/ball_glowb_sphere_cyan.tga
rm textures/wsw_cave1/light_sphere1.tga
rm textures/wsw_cave1/scratchedmetal2_gloss.tga
rm textures/wsw_cave1/stairs1_norm.tga
rm textures/wsw_cave1/ball_glow.tga
# textures/wsw_cave1/scratchedmetal1.tga
rm textures/wsw_cave1/water_flow_dvdu.tga
rm textures/wsw_cave1/ball_gloss.tga
rm textures/wsw_cave1/water_flow_norm.tga
rm textures/wsw_cave1/stairs1.tga
rm textures/wsw_cave1/scratchedmetal2.tga
rm textures/wsw_cave1/ball.ktx
rm textures/wsw_cave1/ball_glowb_alpha.tga
rm textures/wsw_cave1/light_grid.tga
rm textures/wsw_cave1/ball_noise.tga
rm textures/supersymmetry/ledge_02.jpg
rm textures/supersymmetry/poster_01.tga
rm textures/supersymmetry/ledge_01_team.jpg
rm textures/supersymmetry/jump_pad_2_team.tga
rm textures/supersymmetry/neon_02_team.tga
rm textures/supersymmetry/neon_02.tga
rm textures/supersymmetry/neon_01_team.tga
rm textures/supersymmetry/ledge_01.jpg
rm textures/supersymmetry/ledge_02_team.jpg
rm textures/supersymmetry/neon_03.tga
rm textures/supersymmetry/neon_01.tga
rm textures/supersymmetry/lamp_01.jpg
rm textures/supersymmetry/neon_03_team.tga
rm textures/factory/factory_wall_dark_norm.tga
rm textures/factory/trim01.tga
rm textures/factory/armor_base.tga
rm textures/factory/health_base.tga
rm textures/factory/factory_wall_dark.jpg
rm textures/factory/trim_02_verygloss.tga
rm textures/factory/light_norm.tga
rm textures/factory/warehouse_b.tga
rm textures/factory/factory_metal_floor2.tga
rm textures/factory/light.tga
rm textures/factory/factory_metal_floor2_norm.tga
rm textures/factory/factory_pillar2.tga
rm textures/factory/factory_trim_norm.tga
rm textures/factory/factory_metal_floor2_gloss.tga
rm textures/factory/elec_floor_alpha2.tga
rm textures/factory/factory_pillar1_norm.tga
rm textures/factory/pillar03_fx.tga
rm textures/factory/brick_wall.tga
rm textures/factory/elec_floor_alpha.tga
rm textures/factory/base.tga
rm textures/factory/factory_metal_floor_norm.tga
rm textures/factory/factory_wall_team.tga
rm textures/factory/trim_03_norm.tga
rm textures/factory/wall_light_medium_blend.tga
# textures/factory/factory_wall_grey.tga
rm textures/factory/trim_03_blend.tga
rm textures/factory/base_fx.tga
rm textures/factory/warehouse_c.tga
rm textures/factory/orange_border_trans.tga
rm textures/factory/pillar03_gloss.tga
rm textures/factory/factory_pillar2_norm.tga
rm textures/factory/trim_04_decal_norm.tga
rm textures/factory/wall01.tga
rm textures/factory/orange_border_alpha.tga
rm textures/factory/factory_wall_color_add.tga
rm textures/factory/ammo_base.tga
rm textures/factory/factory_wall_dark_gloss.tga
rm textures/factory/pillar03_norm.tga
rm textures/factory/trim_05_blend.tga
rm textures/factory/factory_tile_norm.tga
rm textures/factory/powerup_base.tga
rm textures/factory/trim_05_norm.tga
rm textures/factory/trim_05_gloss.tga
rm textures/factory/light_focus.tga
rm textures/factory/pillar03_alpha.tga
rm textures/factory/trim_02_gloss.tga
rm textures/factory/blx_wt3_lines.tga
rm textures/factory/factory_wall_team_gloss.tga
rm textures/factory/laser_beam2.tga
rm textures/factory/factory_tile.tga
rm textures/factory/trim01_alpha.tga
rm textures/factory/weapon_base.tga
# textures/factory/glass.tga
rm textures/factory/wave_fx.tga
rm textures/factory/brick_wall_norm.tga
rm textures/factory/factory_ceiling_norm.tga
rm textures/factory/pillar03.tga
rm textures/factory/factory_wall.tga
rm textures/factory/laser_beam.tga
rm textures/factory/elec_floor.tga
# textures/factory/factory_wall_norm.tga
rm textures/factory/base_stripes_out.tga
rm textures/factory/trim_05.tga
rm textures/factory/warehouse_a.tga
rm textures/factory/beam_beam.tga
rm textures/factory/trim01_fx.tga
rm textures/factory/orange_border_glow.tga
rm textures/factory/trim01_glow.tga
rm textures/factory/factory_wall_team_norm.tga
rm textures/factory/trim_04_decal.tga
rm textures/factory/out_of_service.jpg
rm textures/factory/factory_wall_team_color.tga
rm textures/factory/light_blend.tga
rm textures/factory/blx_wt3_sky_orange.tga
rm textures/factory/metal_dark_gloss.tga
rm textures/factory/trim_02.tga
rm textures/factory/factory_wall_gloss.tga
rm textures/factory/factory_metal_floor.tga
rm textures/factory/factory_pillar1.tga
rm textures/factory/wall01_alpha.tga
rm textures/factory/trim_04_decal_gloss.tga
rm textures/factory/factory_ceiling.tga
rm textures/factory/factory_trim.tga
rm textures/factory/base_stripes_in.tga
rm textures/factory/wall_light_medium.tga
rm textures/factory/trim_03.tga
rm textures/factory/metal_dark.tga
rm textures/factory/factory_pillar1_gloss.jpg
rm textures/factory/destinations.tga
rm textures/factory/trim_02_norm.tga
rm textures/blx_houses/blx_house5.tga
rm textures/blx_houses/blx_house4.tga
rm textures/blx_houses/blx_streets1.jpg
rm textures/blx_houses/blx_light_h_teamback.tga
rm textures/blx_houses/bLx_cars1.tga
rm textures/blx_houses/blx_build2.tga
rm textures/blx_houses/blx_light_h_team2.tga
rm textures/blx_houses/blx_grid2.tga
rm textures/blx_houses/blx_house3.tga
rm textures/blx_houses/bLx_cars2.tga
rm textures/blx_houses/blx_house1.tga
rm textures/blx_houses/blx_ctf_alpha.tga
rm textures/blx_houses/blx_ctf_teamback1.tga
rm textures/blx_houses/blx_light_h_glow.tga
rm textures/blx_houses/blx_light_h_team1.tga
rm textures/blx_houses/blx_ctf_beta.tga
rm textures/blx_houses/blx_build1.tga
# textures/wsw_flareshalos/small_light_halo_blue.tga
rm textures/wsw_flareshalos/glow_halo_white_flat.tga
# textures/wsw_flareshalos/glow_cone_cyan.tga
rm textures/wsw_flareshalos/glow_cone_white.tga
# textures/wsw_flareshalos/glow_neontube_red.tga
rm textures/wsw_flareshalos/glow_cone_verycyan.tga
rm textures/wsw_flareshalos/glow_halo_blue2_flat.tga
# textures/wsw_flareshalos/flare_sphere_white.tga
# textures/wsw_flareshalos/flare_sphere_cyan.tga
# textures/wsw_flareshalos/flare_sphere_fog_white.tga
# textures/wsw_flareshalos/flare_sphere_orange.tga
rm textures/wsw_flareshalos/glow_neontube_purple.tga
rm textures/wsw_flareshalos/glow_ellipse_white1.tga
# textures/wsw_flareshalos/small_light_halo.tga
rm textures/wsw_flareshalos/glow_rec_orange.tga
# textures/wsw_flareshalos/trim_glow_white.tga
rm textures/wsw_flareshalos/glow_halo_blue2.tga
# textures/wsw_flareshalos/glow_halo_white.tga
rm textures/wsw_flareshalos/flare_neontube_white1.tga
# textures/wsw_flareshalos/glow_neontube_blue.tga
rm textures/wsw_flareshalos/trim_glow_blue.tga
rm textures/sky/pinksky1.blend.ktx
rm textures/sky/indigosky2.blend.ktx
rm textures/sky/violetsky2.blend.ktx
rm textures/sky/pinksky2.blend.ktx
rm textures/sky/purplesky1.blend.ktx
rm textures/sky/violetsky1.blend.ktx
rm textures/sky/indigosky1.blend.ktx
rm textures/sky/purplesky2.blend.ktx
rm textures/sky/orangesky1.blend.ktx
rm textures/sky/orangesky2.blend.ktx
# textures/blx_wtest3/blx_wt3_grey.tga
rm textures/blx_wtest3/blx_wt3_ceil1b.tga
rm textures/blx_wtest3/blx_wt3_rock3-grey.tga
rm textures/blx_wtest3/blx_wt3_wall2_gloss.tga
rm textures/blx_wtest3/blx_wt3_mud1.tga
rm textures/blx_wtest3/blx_wt3_singlestripe_gloss.tga
rm textures/blx_wtest3/blx_wt3_floor4_gloss.tga
rm textures/blx_wtest3/blx_wt3_ceil3_norm.tga
rm textures/blx_wtest3/blx_wt3_crate3.tga
rm textures/blx_wtest3/blx_wt3_ceil2_norm.tga
# textures/blx_wtest3/blx_wt3_pillar2.tga
rm textures/blx_wtest3/blx_wt3_singlestripe2_norm.tga
rm textures/blx_wtest3/blx_wt3_dia_gloss.tga
rm textures/blx_wtest3/blx_wt3_sky.tga
rm textures/blx_wtest3/blx_wt3_floor4_norm.tga
rm textures/blx_wtest3/blx_wt3_singlestripe2.tga
rm textures/blx_wtest3/blx_wt3_tele_dudv.tga
rm textures/blx_wtest3/blx_wt3_lines_gloss.tga
rm textures/blx_wtest3/blx_wt3_wall1_gloss.tga
rm textures/blx_wtest3/blx_wt3_pillar3d_gloss.tga
rm textures/blx_wtest3/blx_wt3_wall5_norm.tga
rm textures/blx_wtest3/blx_wt3_wall3_norm.tga
rm textures/blx_wtest3/blx_wt3_wall1.tga
rm textures/blx_wtest3/blx_wt3_ceil1.tga
rm textures/blx_wtest3/blx_wt3_ceil4_norm.tga
rm textures/blx_wtest3/blx_wt3_glow.tga
rm textures/blx_wtest3/blx_trans_noclip.tga
rm textures/blx_wtest3/blx_wt3_wall4_norm.tga
rm textures/blx_wtest3/blx_wt3_wall4_gloss.jpg
rm textures/blx_wtest3/blx_wt3_singlestripe_norm.tga
rm textures/blx_wtest3/blx_wt3_ceil1b_gloss.tga
rm textures/blx_wtest3/blx_wt3_wall3.jpg
rm textures/blx_wtest3/blx_wt3_ceil1b_norm.tga
rm textures/blx_wtest3/blx_wt3_dia_norm.tga
# textures/blx_wtest3/blx_wt3_pillar3_norm.tga
rm textures/blx_wtest3/blx_wt3_wall3_gloss.jpg
rm textures/blx_wtest3/blx_wt3_surfmetal1.tga
rm textures/blx_wtest3/blx_wt3_crate1.tga
rm textures/blx_wtest3/blx_wt3_rock3-switch.tga
rm textures/blx_wtest3/blx_wt3_floor4.tga
rm textures/blx_wtest3/blx_wt3_rock3_norm.tga
rm textures/blx_wtest3/blx_wt3_rock3-grey-red.tga
rm textures/blx_wtest3/blx_wt3_pillar2_gloss.tga
rm textures/blx_wtest3/blx_wt3_ceil1_norm.tga
rm textures/blx_wtest3/blx_wt3_crate1_norm.tga
rm textures/blx_wtest3/blx_wt3_crate2_norm.tga
# textures/blx_wtest3/blx_wt3_pillar3_gloss.tga
rm textures/blx_wtest3/blx_wt3_lines.tga
rm textures/blx_wtest3/blx_wt3_wall1_norm.tga
rm textures/blx_wtest3/blx_wt3_floor5_norm.tga
rm textures/blx_wtest3/blx_wt3_wall5_gloss.tga
rm textures/blx_wtest3/blx_wt3_pillar3hd_norm.tga
rm textures/blx_wtest3/blx_wt3_ceil2.tga
rm textures/blx_wtest3/blx_wt3_floor6.jpg
# textures/blx_wtest3/blx_wt3_surfmetal3.tga
rm textures/blx_wtest3/blx_wt3_pillar3d.tga
rm textures/blx_wtest3/blx_wt3_pillar.tga
rm textures/blx_wtest3/blx_wt3_ceil1_gloss.tga
rm textures/blx_wtest3/blx_wt3_wall2_norm.tga
rm textures/blx_wtest3/water_normalmap.jpg
# textures/blx_wtest3/blx_wt3_pillar3.tga
rm textures/blx_wtest3/blx_wt3_lines_norm.tga
rm textures/blx_wtest3/blx_wt3_dgrey.tga
rm textures/blx_wtest3/blx_wt3_ceil4_gloss.tga
rm textures/blx_wtest3/blx_wt3_mud1_norm.tga
rm textures/blx_wtest3/blx_wt3_pillar3hd.tga
rm textures/blx_wtest3/blx_wt3_pillar_gloss.tga
rm textures/blx_wtest3/blx_wt3_ceil4.tga
rm textures/blx_wtest3/blx_wt3_wall2.tga
rm textures/blx_wtest3/blx_wt3_rock3-switch-red.tga
rm textures/blx_wtest3/blx_wt3_pillar2_norm.tga
rm textures/blx_wtest3/blx_wt3_ceil2_gloss.tga
rm textures/blx_wtest3/blx_wt3_rock3.tga
rm textures/blx_wtest3/blx_wt3_ceil3_gloss.tga
rm textures/blx_wtest3/blx_wt3_dia.tga
rm textures/blx_wtest3/blx_wt3_pillar3hd_gloss.tga
# textures/blx_wtest3/blx_wt3_surfmetal_gloss.tga
rm textures/blx_wtest3/blx_wt3_wall4.jpg
# textures/blx_wtest3/blx_wt3_surfmetal2.tga
rm textures/blx_wtest3/blx_wt3_floor5.tga
rm textures/blx_wtest3/blx_wt3_singlestripe.tga
rm textures/blx_wtest3/blx_wt3_crate3_norm.tga
rm textures/blx_wtest3/blx_wt3_rock3-grey_norm.tga
rm textures/blx_wtest3/blx_wt3_floor6_norm.tga
rm textures/blx_wtest3/blx_wt3_pillar_norm.tga
rm textures/blx_wtest3/blx_wt3_wall5.tga
rm textures/blx_wtest3/blx_wt3_ceil3.tga
rm textures/blx_wtest3/blx_wt3_crate2.tga
rm textures/blx_wtest3/blx_wt3_singlestripe2_gloss.tga
rm textures/bricks/bricks1.ktx
rm textures/bricks/redbricks_trim_01_norm.tga
rm textures/bricks/redbricks_base_01_norm.tga
rm textures/bricks/bricks2.ktx
rm textures/bricks/redbricks_base_02_norm.tga
rm textures/bricks/bricks1_norm.tga
# textures/bricks/redbricks_base_01.ktx
rm textures/bricks/blackbricks_base_01.ktx
rm textures/bricks/bricks2_norm.tga
rm textures/bricks/redbricks_base_02.ktx
rm textures/bricks/blackbricks_base_01_norm.tga
rm textures/bricks/redbricks_trim_01.ktx
rm textures/blx_tech2/tech2_light_1_gloss.tga
rm textures/blx_tech2/tech2_base_mid_norm.tga
rm textures/blx_tech2/tech2_circle1_norm.tga
rm textures/blx_tech2/tech2_light_1_blend.tga
rm textures/blx_tech2/tech2_base_mid_purple.tga
rm textures/blx_tech2/tech2_base_bright.tga
rm textures/blx_tech2/tech2_base_mid_red_gloss.tga
rm textures/blx_tech2/tech2_base_mid_red.tga
rm textures/blx_tech2/tech2_wall_2a_c_blend.tga
rm textures/blx_tech2/tech2_circle1_gloss.tga
rm textures/blx_tech2/tech2_base_mid_gloss.tga
rm textures/blx_tech2/tech2_wall_2a_blend.tga
rm textures/blx_tech2/tech2_wall_3.tga
rm textures/blx_tech2/tech2_floor_mid_norm.tga
rm textures/blx_tech2/tech2_circle1.tga
rm textures/blx_tech2/tech2_wall_2b_blend.tga
rm textures/blx_tech2/tech2_wall_2a_b_blend.tga
rm textures/blx_tech2/tech2_wall_3a.tga
rm textures/blx_tech2/tech2_base_edge_2.tga
rm textures/blx_tech2/tech2_base_mid_green.tga
rm textures/blx_tech2/tech2_circle1_blend.tga
rm textures/blx_tech2/tech2_wall_2a_b_gloss.tga
rm textures/blx_tech2/tech2_wall_2a.tga
rm textures/blx_tech2/tech2_wall_2c_blend.tga
rm textures/blx_tech2/tech2_circle1_height.tga
rm textures/blx_tech2/tech2_light_1_norm.tga
rm textures/blx_tech2/tech2_wall_3b.tga
rm textures/blx_tech2/tech2_wall_2_gloss.tga
rm textures/blx_tech2/tech2_base_mid_green_gloss.tga
rm textures/blx_tech2/tech2_chrome_gloss.tga
rm textures/blx_tech2/tech2_wall_3b_gloss.tga
rm textures/blx_tech2/tech2_base_mid_purple_norm.tga
rm textures/blx_tech2/tech2_floor_mid.tga
rm textures/blx_tech2/tech2_base_line.tga
rm textures/blx_tech2/tech2_base_mid_purple_gloss.tga
rm textures/blx_tech2/tech2_wall_2c_gloss.tga
rm textures/blx_tech2/tech2_wall_2a_c.tga
rm textures/blx_tech2/tech2_base_green.tga
rm textures/blx_tech2/tech2_wall_2a_b.tga
rm textures/blx_tech2/tech2_wall_2a_gloss.tga
rm textures/blx_tech2/tech2_wall_2_blend.tga
rm textures/blx_tech2/tech2_wall_3a_gloss.tga
rm textures/blx_tech2/tech2_base_dark_green.tga
rm textures/blx_tech2/tech2_base_dark_red.tga
rm textures/blx_tech2/tech2_base_mid_red_norm.tga
rm textures/blx_tech2/tech2_base_mid_green_norm.tga
rm textures/blx_tech2/tech2_wall_2a_c_gloss.tga
rm textures/blx_tech2/tech2_wall_2.tga
rm textures/blx_tech2/tech2_base_dark.tga
rm textures/blx_tech2/tech2_base_mid.tga
rm textures/blx_tech2/tech2_grate.tga
rm textures/blx_tech2/tech2_chrome.tga
rm textures/blx_tech2/tech2_wall_3_gloss.tga
rm textures/blx_tech2/tech2_base_dark_purple.tga
rm textures/blx_tech2/tech2_wall_2b.tga
rm textures/blx_tech2/tech2_wall_2c.tga
rm textures/blx_tech2/tech2_floor_mid_height.tga
rm textures/blx_tech2/tech2_light_1.tga
rm textures/blx_tech2/tech2_base_edge.tga
rm textures/decals/evilface_stamp.tga
rm textures/decals/xmarksthespot_decal.tga
# textures/decals/trafficline04stripes.tga
# textures/decals/trafficline04b.tga
rm textures/decals/orangearrows_outlined.tga
rm textures/decals/trafficline04redandwhitestripes2.tga
rm textures/decals/posterbigbobot.tga
# textures/decals/trafficline04yellow.tga
# textures/decals/plasterworn0030.ktx
rm textures/decals/posterbigpadpork.tga
rm textures/decals/posterbigwarsow.tga
rm textures/decals/beta.tga
rm textures/decals/posterbigmonada.tga
# textures/decals/sign_up01.tga
# textures/decals/poster_monada.tga
rm textures/decals/0080.ktx
# textures/decals/trafficline04.tga
rm textures/decals/team_beta_stain002.tga
# textures/decals/poster_smallbunch.tga
rm textures/decals/trafficline04yellowstripes.tga
# textures/decals/graffiti_01.tga
rm textures/decals/team_alpha_stain001.tga
# textures/decals/sign_warning01.tga
rm textures/decals/team_alpha_stain005.tga
rm textures/decals/trafficline04redstripes.tga
# textures/decals/trafficline04orange.tga
# textures/decals/plasterbroken01.tga
rm textures/decals/stain004.tga
# textures/decals/trafficline04byellow.tga
rm textures/decals/A.tga
rm textures/decals/stain002.tga
# textures/decals/poster01.tga
rm textures/decals/team_beta_stain005.tga
# textures/decals/trafficline04stripes2.tga
# textures/decals/trafficline04orangestripes2.tga
rm textures/decals/leavedead01.tga
rm textures/decals/team_alpha_stain004.tga
rm textures/decals/stain001.tga
# textures/decals/poster_bobot.tga
rm textures/decals/team_beta_stain001.tga
rm textures/decals/team_alpha_stain003.tga
# textures/decals/graffiti_03.tga
# textures/decals/poster_padpork.tga
# textures/decals/trafficline04yellowstripes2.tga
# textures/decals/graffiti_02.tga
# textures/decals/trafficline04redstripes2.tga
rm textures/decals/B.tga
rm textures/decals/alpha.tga
rm textures/decals/team_alpha_stain002.tga
rm textures/decals/kiki.tga
rm textures/decals/sign_circuit02.tga
rm textures/decals/poster_weapons.tga
rm textures/decals/trafficline04orangestripes.tga
rm textures/decals/wdm17easteregg.tga
rm textures/decals/stain005.tga
# textures/decals/leavesdead01.tga
rm textures/decals/thewall.tga
# textures/decals/graffityPERON32.tga
rm textures/decals/team_beta_stain003.tga
rm textures/decals/team_alpha_stain006.tga
rm textures/decals/stain003.tga
rm textures/decals/team_beta_stain004.tga
rm textures/decals/sign_circuit01.tga
rm textures/decals/team_beta_stain006.tga
rm textures/decals/plasterbroken01_norm.tga
rm textures/decals/trafficline04red.tga
# textures/decals/orangearrows.tga
# textures/decals/graffityTEAMZISSOU32.tga
# textures/cleansurface/pantone432c.tga
# textures/cleansurface/pantone425c.tga
rm textures/cleansurface/black.tga
# textures/cleansurface/pantonecoolgray10c.tga
rm textures/cleansurface/pantone2746c.tga
rm textures/cleansurface/pantone363c.tga
rm textures/cleansurface/pantone361c.tga
rm textures/cleansurface/pantone7536c.tga
rm textures/cleansurface/pantone4685c.tga
rm textures/cleansurface/pantone2727c.tga
rm textures/refly_trims/36hazard_gloss.tga
rm textures/refly_trims/36hazard.tga
rm textures/refly_trims/36hazard_norm.tga
rm textures/refly_trims/hazardline.tga
# textures/wood/woodplank02.ktx
rm textures/wood/woodplank04.tga
rm textures/wood/woodplank01_norm.tga
rm textures/wood/testwood1.ktx
rm textures/wood/woodold01_norm.tga
rm textures/wood/testwood1_spec.tga
rm textures/wood/woodold01.ktx
# textures/wood/woodplank01.ktx
# textures/wood/woodplank03.ktx
rm textures/wood/woodtables01_norm.tga
# textures/wood/woodtables01.ktx
rm textures/wood/woodplank05.ktx
rm textures/wood/testwood1_norm.tga
rm textures/wood/woodplank05_norm.tga
rm textures/wood/woodplank04_norm.tga
rm textures/refly_stone/zadaz.tga
rm textures/refly_stone/concrete1_norm.tga
rm textures/refly_stone/concrete1.tga
rm textures/baxandall/poster_01.tga
rm textures/baxandall/baxandall_sign_04.tga
rm textures/baxandall/item_indi_2.tga
rm textures/baxandall/grid_02.jpg
rm textures/baxandall/teleglow_02.tga
rm textures/baxandall/neon_02.tga
rm textures/baxandall/item_indi_3.tga
rm textures/baxandall/item_indi_1.tga
rm textures/baxandall/grid_03.jpg
rm textures/baxandall/jump_pad_2.tga
rm textures/baxandall/neon_07.tga
rm textures/baxandall/grid_01.jpg
rm textures/baxandall/trim_01_gloss.jpg
rm textures/baxandall/baxandall_sign_03.tga
rm textures/baxandall/trim_01.jpg
rm textures/baxandall/teleglow_01.tga
rm textures/baxandall/baxandall_sign_01.tga
rm textures/baxandall/jump_pad_1.tga
rm textures/baxandall/neon_06.tga
rm textures/baxandall/neon_09.tga
rm textures/baxandall/item_indi_4.tga
rm textures/baxandall/neon_01.tga
rm textures/baxandall/trim_01_norm.jpg
rm textures/baxandall/baxandall_sign_02.tga
rm textures/baxandall/lamp_01.jpg
rm textures/baxandall/warning_sign_01.tga
rm textures/baxandall/neon_08.tga
rm textures/baxandall/item_indi_2_green.tga
rm textures/terrain/rocks003_512x512_norm.tga
rm textures/terrain/rocks003_512x512.ktx
rm textures/36_others/36sky3.tga
rm textures/36_others/36sky2.tga
rm textures/blx_grey/blx_grey_wall_6.tga
rm textures/blx_grey/blx_grey_neon_q.tga
rm textures/blx_grey/blx_grey_spacer.tga
rm textures/blx_grey/blx_grey_wall_5_alpha.tga
rm textures/blx_grey/blx_grey_wall_3.tga
rm textures/blx_grey/blx_grey_wall_2a.tga
rm textures/blx_grey/blx_grey_wall_1_alpha.tga
rm textures/blx_grey/blx_grey_circuits_blue_512.tga
rm textures/blx_grey/blx_grey_circuits_red_512.tga
rm textures/blx_grey/blx_grey_grid.tga
rm textures/blx_grey/blx_grey_wall_2b.tga
rm textures/blx_grey/blx_grey_grid_alpha.tga
rm textures/blx_grey/blx_grey_floor_1_alpha.tga
rm textures/blx_grey/blx_grey_tile.tga
rm textures/blx_grey/blx_grey_md_lt_B.tga
rm textures/blx_grey/blx_grey_ecel_bounce_blend.tga
rm textures/blx_grey/blx_grey_wall_7_alpha.tga
rm textures/blx_grey/blx_grey_spacer_alpha.tga
rm textures/blx_grey/blx_grey_light_blue.jpg
rm textures/blx_grey/blx_grey_md_lt_B_alpha.tga
rm textures/blx_grey/blx_grey_plane_lt.tga
rm textures/blx_grey/blx_grey_plane_md.tga
rm textures/blx_grey/blx_grey_tech_1.tga
rm textures/blx_grey/blx_grey_wall_5.tga
rm textures/blx_grey/blx_grey_wall_2_alpha.tga
rm textures/blx_grey/blx_grey_md_lt.tga
rm textures/blx_grey/blx_grey_wall_1.tga
rm textures/blx_grey/blx_grey_ecel_bounce.tga
rm textures/blx_grey/blx_grey_dec.tga
rm textures/blx_grey/blx_grey_wall_3_alpha.tga
rm textures/blx_grey/blx_grey_wall_1a.jpg
rm textures/blx_grey/blx_grey_light_rh.tga
rm textures/blx_grey/blx_grey_wall_2a_alpha.tga
rm textures/blx_grey/blx_grey_floor_1.tga
rm textures/blx_grey/blx_grey_circuits_surface_512.tga
rm textures/blx_grey/blx_grey_tile_alpha.tga
# textures/blx_grey/blx_grey_light_h.tga
rm textures/blx_grey/blx_grey_plane_dk.tga
rm textures/blx_grey/blx_grey_md_lt_alpha.tga
rm textures/blx_grey/blx_grey_circuits_white_512.tga
rm textures/blx_grey/blx_grey_wall_4.tga
rm textures/blx_grey/blx_grey_wall_2.tga
rm textures/blx_grey/blx_grey_dark.tga
rm textures/blx_grey/bLx_grey_ecel_bounce_small.jpg
rm textures/blx_grey/blx_grey_wall_7.tga
rm textures/blx_grey/blx_grey_dark_ws.tga
rm textures/world/wdm4/foglayer.tga
rm textures/hexagons/metalwallceilling01_norm.tga
rm textures/hexagons/pavementfloor01.tga
rm textures/hexagons/pavementfloor_trim_orangeandgrey.tga
rm textures/hexagons/metallight01.jpg
rm textures/hexagons/metalfloor01_norm.tga
rm textures/hexagons/hexagons2.jpg
rm textures/hexagons/metalwall02.jpg
rm textures/hexagons/metalwallceilling02.tga
rm textures/hexagons/pavementfloor01_norm.tga
# textures/hexagons/pavementfloor_trim_redandwhite.tga
rm textures/hexagons/pavementfloor_trim_yellow.tga
rm textures/hexagons/warningtrim01_gloss.tga
# textures/hexagons/pavementfloor_trim_greyandwhite.tga
rm textures/hexagons/hexagons.jpg
rm textures/hexagons/stonecollumn01.tga
rm textures/hexagons/metalcollumn01_gloss.tga
# textures/hexagons/pavementfloor_trim_red.tga
rm textures/hexagons/warningtrim01.tga
rm textures/hexagons/pavementfloor_trim.tga
# textures/hexagons/pavementfloor_trim_whiteandgrey.tga
rm textures/hexagons/metalwallceilling03_norm.tga
rm textures/hexagons/metalwallceilling02_gloss.tga
rm textures/hexagons/blue.tga
rm textures/hexagons/stonecollumn01_norm.tga
rm textures/hexagons/metalwallceilling01.tga
rm textures/hexagons/tinwall01.jpg
rm textures/hexagons/metalwallceilling03.tga
rm textures/hexagons/metalcollumn01_norm.tga
rm textures/hexagons/rail02.jpg
rm textures/hexagons/darkblue.jpg
rm textures/hexagons/hexabump.tga
rm textures/hexagons/pavementfloor_trim_yellowandwhite.tga
# textures/hexagons/pavementfloor_trim_white.tga
rm textures/hexagons/metalfloor01_gloss.tga
rm textures/hexagons/metalfloor01.tga
rm textures/hexagons/metalcollumn01.tga
# textures/hexagons/pavementfloor_trim_norm.tga
# textures/hexagons/pavementfloor_trim_orange.tga
rm textures/hexagons/metalwallceilling01_gloss.tga
rm textures/hexagons/warningtrim01_norm.tga
rm textures/hexagons/rail01.jpg
rm textures/hexagons/metallight02.jpg
rm textures/hexagons/pavementfloor_trim_redandgrey.tga
rm textures/hexagons/metalwall01.jpg
# textures/hexagons/pavementfloor_trim_orangeandwhite.tga
rm textures/hexagons/metalwallceilling02_norm.tga
rm textures/wsw_city1/grate_norm.tga
rm textures/wsw_city1/wires2.ktx
rm textures/wsw_city1/slateround_norm.tga
rm textures/wsw_city1/tech_wall7.tga
rm textures/wsw_city1/tech_concrete_pattern_inv.ktx
rm textures/wsw_city1/tech_wall1_norm.tga
rm textures/wsw_city1/concrete3.ktx
rm textures/wsw_city1/concrete1_height.tga
rm textures/wsw_city1/team_blue_lightstrip.tga
rm textures/wsw_city1/tech_wall2_gloss.tga
rm textures/wsw_city1/clouds_layer1.ktx
rm textures/wsw_city1/cables2.tga
rm textures/wsw_city1/grid_norm.tga
rm textures/wsw_city1/team_lightstrip.tga
rm textures/wsw_city1/grid2_norm.tga
rm textures/wsw_city1/plate_tile2_gloss.tga
rm textures/wsw_city1/wires4.tga
rm textures/wsw_city1/base_lightblue_big.ktx
rm textures/wsw_city1/clouds_layer2_norm.tga
rm textures/wsw_city1/cables1_norm.tga
rm textures/wsw_city1/concret7.ktx
rm textures/wsw_city1/slateround.ktx
rm textures/wsw_city1/e6tdoor.jpg
rm textures/wsw_city1/tech_dirt1_norm.tga
rm textures/wsw_city1/plate_tile1_norm.tga
rm textures/wsw_city1/wires5_norm.tga
rm textures/wsw_city1/wires4_norm.tga
rm textures/wsw_city1/blue_light.tga
rm textures/wsw_city1/tech_wall2.tga
rm textures/wsw_city1/plate_tile1_gloss.tga
rm textures/wsw_city1/rollupdoor1_gloss.tga
rm textures/wsw_city1/wires5.ktx
# textures/wsw_city1/9techwall01_gloss.ktx
rm textures/wsw_city1/team_red_lightstrip.tga
rm textures/wsw_city1/skyscraper1_blend.tga
rm textures/wsw_city1/orange_light.tga
rm textures/wsw_city1/concrete3_norm.tga
rm textures/wsw_city1/wires3.ktx
rm textures/wsw_city1/plate_tile2_norm.tga
rm textures/wsw_city1/tech_concrete_pattern_dark_mate.ktx
rm textures/wsw_city1/tubes1_gloss.tga
rm textures/wsw_city1/tech_wall4.ktx
rm textures/wsw_city1/plate_tile2.tga
rm textures/wsw_city1/window_tall01_norm.tga
rm textures/wsw_city1/grid_a_norm.tga
# textures/wsw_city1/tech_concrete_pattern_norm.tga
rm textures/wsw_city1/metal1_norm.tga
rm textures/wsw_city1/plate_tile1.tga
# textures/wsw_city1/tech_concrete_tiles.ktx
rm textures/wsw_city1/tech_wall6.tga
# textures/wsw_city1/tech_wall3_gloss.tga
rm textures/wsw_city1/tech_wall4_norm.tga
rm textures/wsw_city1/blue_concret.tga
# textures/wsw_city1/9techwall01_add2.ktx
# textures/wsw_city1/9techwall01.ktx
rm textures/wsw_city1/slateround_gloss.tga
rm textures/wsw_city1/circle1.ktx
rm textures/wsw_city1/blue_beam2.tga
rm textures/wsw_city1/stepside01_gloss.tga
rm textures/wsw_city1/tech_concrete_gloss.tga
rm textures/wsw_city1/blue_lightstripes.tga
rm textures/wsw_city1/window_tall01_gloss.tga
rm textures/wsw_city1/wires1_norm.tga
# textures/wsw_city1/townsign01.tga
# textures/wsw_city1/light_bulb_top.tga
rm textures/wsw_city1/clouds_layer1_norm.tga
rm textures/wsw_city1/stepside02.tga
# textures/wsw_city1/tech_wall5.tga
rm textures/wsw_city1/grid2.tga
rm textures/wsw_city1/light_bulb_corona2.tga
rm textures/wsw_city1/concret7_norm.tga
rm textures/wsw_city1/skyscraper1.tga
# textures/wsw_city1/grate.ktx
rm textures/wsw_city1/tech_wall1.tga
rm textures/wsw_city1/light_bulb_lamp_inside.tga
rm textures/wsw_city1/tech_wall4_gloss.tga
rm textures/wsw_city1/tech_wall8.ktx
rm textures/wsw_city1/stepside01_norm.tga
rm textures/wsw_city1/metal1.ktx
rm textures/wsw_city1/townsign02.tga
rm textures/wsw_city1/tech_dirt1.tga
rm textures/wsw_city1/tech_concrete_pattern_gloss.tga
rm textures/wsw_city1/tech_dirt1_gloss.tga
rm textures/wsw_city1/blue_beam1.tga
rm textures/wsw_city1/tech_wall3.tga
rm textures/wsw_city1/tech_concrete_norm.tga
rm textures/wsw_city1/cables2_norm.tga
rm textures/wsw_city1/grid_a.ktx
rm textures/wsw_city1/tech_concrete_tiles_gloss.tga
rm textures/wsw_city1/cables1.ktx
rm textures/wsw_city1/rollupdoor1old_norm.jpg
rm textures/wsw_city1/clouds_layer2.ktx
rm textures/wsw_city1/metalsheet1.tga
rm textures/wsw_city1/rollupdoor1.ktx
# textures/wsw_city1/tech_concrete_tiles_norm.tga
rm textures/wsw_city1/purple_light.tga
rm textures/wsw_city1/wires3_norm.tga
rm textures/wsw_city1/metalsheet1_norm.tga
rm textures/wsw_city1/grid.ktx
rm textures/wsw_city1/red_light_oval.tga
rm textures/wsw_city1/concrete1_norm.tga
rm textures/wsw_city1/stepside01.tga
# textures/wsw_city1/light_bulb_side.tga
# textures/wsw_city1/9techwall01_add1.ktx
rm textures/wsw_city1/concrete1.tga
rm textures/wsw_city1/window_tall01.tga
rm textures/wsw_city1/tech_wall1_gloss.tga
# textures/wsw_city1/tech_wall3_norm.tga
# textures/wsw_city1/tech_concrete_pattern_mate.ktx
rm textures/wsw_city1/tubes1_norm.tga
# textures/wsw_city1/wires1.tga
rm textures/wsw_city1/tech_concrete_pattern.ktx
rm textures/wsw_city1/chrome.jpg
# textures/wsw_city1/light_bulb_corona.tga
# textures/wsw_city1/9techwall01_norm.jpg
rm textures/wsw_city1/blx_glow_noise.tga
rm textures/wsw_city1/rollupdoor1_norm.tga
# textures/wsw_city1/tubes1.tga
rm textures/cha0s_ws/trim2_norm.tga
rm textures/cha0s_ws/floor_pitrows_128_gloss.tga
rm textures/cha0s_ws/flat_lt_gloss.tga
rm textures/cha0s_ws/cement-tiled_grey_norm.tga
rm textures/cha0s_ws/flat_dk.ktx
rm textures/cha0s_ws/floor_pitrows_128.tga
rm textures/cha0s_ws/flat_dk_norm.jpg
rm textures/cha0s_ws/trim19_norm.tga
rm textures/cha0s_ws/cement_1_stripes_256_norm.tga
rm textures/cha0s_ws/cement_1_clean.ktx
rm textures/cha0s_ws/base_grey_norm.jpg
rm textures/cha0s_ws/cement-tiled.ktx
rm textures/cha0s_ws/cement_2.tga
rm textures/cha0s_ws/cement_2_yellow.tga
rm textures/cha0s_ws/concrete-pit-rows_stripes_norm.tga
rm textures/cha0s_ws/base_brown.jpg
rm textures/cha0s_ws/base_brown_line.jpg
rm textures/cha0s_ws/base_yellow_norm.jpg
rm textures/cha0s_ws/cement_1_grimy.ktx
rm textures/cha0s_ws/neon2.tga
# textures/cha0s_ws/ch_sky_night_front.tga
rm textures/cha0s_ws/cement_2_yellow_trim_norm.jpg
rm textures/cha0s_ws/cement_1_clean_gloss.tga
rm textures/cha0s_ws/concrete-pit-rows_gloss.tga
rm textures/cha0s_ws/base_yellow.tga
rm textures/cha0s_ws/flat_dk_logo_gloss.tga
rm textures/cha0s_ws/trim_yellow.jpg
rm textures/cha0s_ws/base_floor_norm.jpg
rm textures/cha0s_ws/base_wall.tga
rm textures/cha0s_ws/flat_dk_logo_norm.tga
rm textures/cha0s_ws/cement_2_yellow_flat_norm.jpg
# textures/cha0s_ws/chrome4.tga
rm textures/cha0s_ws/cement_2_height.tga
rm textures/cha0s_ws/concrete-pit-rows.tga
rm textures/cha0s_ws/cement-tiled_grey_gloss.tga
rm textures/cha0s_ws/big-blue-cement_norm.tga
rm textures/cha0s_ws/neon1.tga
rm textures/cha0s_ws/cement_3_stripes.tga
rm textures/cha0s_ws/big-blue-cement_norm.jpg
rm textures/cha0s_ws/concrete-pit-rows_stripes_gloss.tga
rm textures/cha0s_ws/flat_lt_norm.jpg
rm textures/cha0s_ws/cement-tiled-yellow_norm.tga
rm textures/cha0s_ws/cement-tiled_norm.tga
rm textures/cha0s_ws/base_wall_norm.jpg
rm textures/cha0s_ws/trim2_gloss.tga
rm textures/cha0s_ws/cement-tiled-yellow.ktx
rm textures/cha0s_ws/cement_3.tga
rm textures/cha0s_ws/flat_lt.tga
rm textures/cha0s_ws/cement_1_gunky.ktx
rm textures/cha0s_ws/phonograph_bronze_3.tga
rm textures/cha0s_ws/trim19_grey.jpg
rm textures/cha0s_ws/cement_1_stripes_norm.tga
rm textures/cha0s_ws/cement-tiled_grey.jpg
rm textures/cha0s_ws/concrete-pit-rows_stripes.tga
rm textures/cha0s_ws/cement_floor_lt.tga
rm textures/cha0s_ws/trim19_black.jpg
rm textures/cha0s_ws/base_column.tga
rm textures/cha0s_ws/trim19_gloss.tga
rm textures/cha0s_ws/cement_2_norm.tga
rm textures/cha0s_ws/sw_xlight.tga
rm textures/cha0s_ws/trim2.tga
rm textures/cha0s_ws/cement_floor_lt_norm.tga
rm textures/cha0s_ws/base_grey.tga
rm textures/cha0s_ws/big-blue-cement.tga
rm textures/cha0s_ws/ch_sky_night_back.tga
rm textures/cha0s_ws/trim19.tga
rm textures/cha0s_ws/blocks_1_top_lip.tga
rm textures/cha0s_ws/cement_3_norm.tga
rm textures/cha0s_ws/base_grey_gloss.tga
rm textures/cha0s_ws/cement_2_yellow_trim.tga
rm textures/cha0s_ws/base_brown_logo.jpg
rm textures/cha0s_ws/floor_pitrows_128_norm.tga
rm textures/cha0s_ws/cement_grey.jpg
rm textures/cha0s_ws/blocks_1_top_lip_norm.jpg
# textures/cha0s_ws/dirt.tga
rm textures/cha0s_ws/cement_2_yellow_norm.jpg
rm textures/cha0s_ws/phonograph_slate_2.tga
rm textures/cha0s_ws/concrete-pit-rows_norm.tga
rm textures/cha0s_ws/base_floor.tga
rm textures/cha0s_ws/concrete-pit-rows_bump.jpg
rm textures/cha0s_ws/neon1.blend.tga
rm textures/cha0s_ws/cement_2_yellow_flat.tga
rm textures/cha0s_ws/flat_dk_logo.tga
rm textures/cha0s_ws/ceiling_grey.jpg
rm textures/common/nolightmap.jpg
rm textures/common/playerclip.jpg
rm textures/common/donotenter.jpg
rm textures/common/noimpact.jpg
rm textures/common/terrain.jpg
rm textures/common/trigger.jpg
rm textures/common/caulk.jpg
rm textures/common/ladder.jpg
rm textures/common/nodrop.jpg
rm textures/common/origin.jpg
rm textures/common/areaportal.jpg
rm textures/common/hint.jpg
rm textures/common/mirror.jpg
rm textures/common/nowalljumpclip.jpg
rm textures/common/skip.jpg
rm textures/common/nodraw.jpg
rm textures/common/invisible.jpg
rm textures/common/nodrawnonsolid.jpg
rm textures/common/slick.jpg
rm textures/common/fullclip.jpg
rm textures/ETRtex/TEAMZISSOU32.tga
rm textures/ETRtex/PERON32.tga
# textures/leaves/leaves0108_s.tga
rm textures/boqu2/darkgreytrim_gloss.tga
rm textures/boqu2/metaltrim2_gloss.tga
rm textures/boqu2/longwhitetile_gloss.tga
rm textures/boqu2/squaretilewhite.tga
rm textures/boqu2/vent3_norm.tga
rm textures/boqu2/rocks8_gloss.tga
rm textures/boqu2/floorplates3.tga
rm textures/boqu2/whitetrim3_gloss.tga
rm textures/boqu2/darkgreytrim2_norm.tga
rm textures/boqu2/3neon_norm.tga
rm textures/boqu2/concrete_tile_dark_gloss.tga
rm textures/boqu2/darkgreytrim2_gloss.tga
rm textures/boqu2/greypanel6_norm.tga
rm textures/boqu2/concrete_tile_dark_norm.tga
rm textures/boqu2/rock9_norm.tga
rm textures/boqu2/wallsp2.tga
rm textures/boqu2/whitetrim6_gloss.tga
rm textures/boqu2/metaltrim_gloss.tga
rm textures/boqu2/concrete4_norm.tga
rm textures/boqu2/bigwhitetiles3_gloss.tga
rm textures/boqu2/vent3_gloss.tga
rm textures/boqu2/darkgreytrim2.tga
rm textures/boqu2/storagepanellight2.tga
rm textures/boqu2/whitetrim6_norm.tga
rm textures/boqu2/2neon_blue_norm.tga
rm textures/boqu2/wallsp2_gloss.tga
rm textures/boqu2/brighttechpanel4_norm.tga
rm textures/boqu2/floorplates2_norm.tga
rm textures/boqu2/floorplates4_gloss.tga
rm textures/boqu2/storagepanellight_decal.tga
rm textures/boqu2/wallsp1_gloss.tga
rm textures/boqu2/brighttechpanel4.tga
rm textures/boqu2/whitetrim3.tga
rm textures/boqu2/floorplates4_norm.tga
rm textures/boqu2/vent4.tga
rm textures/boqu2/whitetrim7_gloss.tga
rm textures/boqu2/squaretilewhite_norm.tga
rm textures/boqu2/whitetrim7.tga
rm textures/boqu2/darkpanel_gloss.tga
rm textures/boqu2/longwhitetile.tga
rm textures/boqu2/bigwhitetiles3_norm.tga
rm textures/boqu2/wallsp1.tga
rm textures/boqu2/floorplates3_gloss.tga
rm textures/boqu2/darkgreytrim.tga
rm textures/boqu2/tele_decal2_blue.tga
rm textures/boqu2/metaltrim3_gloss.tga
rm textures/boqu2/wallsp3.tga
rm textures/boqu2/floorplates_gloss.tga
rm textures/boqu2/brighttechpanel5_gloss.tga
rm textures/boqu2/metaltrim2.tga
rm textures/boqu2/holohealth.tga
rm textures/boqu2/3neon_decal.tga
rm textures/boqu2/metalplates.tga
rm textures/boqu2/2neon_blue_decal.tga
rm textures/boqu2/brighttechpanel4_gloss.tga
rm textures/boqu2/floorplates4.tga
rm textures/boqu2/blueblacktrim_gloss.tga
rm textures/boqu2/floorplates_norm.tga
rm textures/boqu2/concrete_tile_gloss.tga
rm textures/boqu2/metalplates_gloss.tga
rm textures/boqu2/o2pipe_gloss.tga
rm textures/boqu2/3neon_gloss.tga
rm textures/boqu2/storagepanellight.tga
rm textures/boqu2/wallsp1_norm.tga
rm textures/boqu2/concrete4_gloss.tga
rm textures/boqu2/2neon_blue_gloss.tga
rm textures/boqu2/whitepanels2_gloss.tga
rm textures/boqu2/whitepanels2_norm.tga
rm textures/boqu2/darkgreytrim_norm.tga
rm textures/boqu2/vent4_norm.tga
rm textures/boqu2/metaltrim.tga
rm textures/boqu2/metaltrim_norm.tga
rm textures/boqu2/o2pipe.tga
rm textures/boqu2/brighttechpanel5_norm.tga
rm textures/boqu2/greypanel6_gloss.tga
rm textures/boqu2/longwhitetile_norm.tga
rm textures/boqu2/2neon_blue.tga
rm textures/boqu2/storagepanellight_norm.tga
rm textures/boqu2/concrete_tile_norm.tga
rm textures/boqu2/vent3.tga
rm textures/boqu2/wallsp2_norm.tga
rm textures/boqu2/metaltrim1_norm.tga
rm textures/boqu2/rocks8_norm.tga
rm textures/boqu2/darkpanel_norm.tga
rm textures/boqu2/metaltrim2_norm.tga
rm textures/boqu2/whitetrim4_gloss.tga
rm textures/boqu2/bigwhitetiles4.tga
rm textures/boqu2/rocks8.tga
rm textures/boqu2/brighttechpanel5.tga
rm textures/boqu2/bigwhitetiles4_gloss.tga
rm textures/boqu2/whitewallpanels3.tga
rm textures/boqu2/whitetrim4.tga
rm textures/boqu2/3neon.tga
rm textures/boqu2/bigwhitetiles4_norm.tga
rm textures/boqu2/metaltrim3_norm.tga
rm textures/boqu2/storagepanellight_gloss.tga
rm textures/boqu2/whitetrim4_norm.tga
rm textures/boqu2/metalplates_norm.tga
rm textures/boqu2/concrete_tile_dark.tga
rm textures/boqu2/whitepanels2.tga
rm textures/boqu2/rock9_gloss.tga
rm textures/boqu2/whitewallpanels3_norm.tga
rm textures/boqu2/bigwhitetiles3.tga
rm textures/boqu2/tele_decal1_blue.tga
rm textures/boqu2/o2pipe_norm.tga
rm textures/boqu2/whitetrim5.tga
rm textures/boqu2/floorplates2_gloss.tga
rm textures/boqu2/holo1.tga
rm textures/boqu2/whitetrim6.tga
rm textures/boqu2/metaltrim3.tga
rm textures/boqu2/greypanel6.tga
rm textures/boqu2/metalpanel3.tga
rm textures/boqu2/rock9.tga
rm textures/boqu2/blueblacktrim_norm.tga
rm textures/boqu2/wallsp3_norm.tga
rm textures/boqu2/whitewallpanels3_gloss.tga
rm textures/boqu2/whitetrim3_norm.tga
rm textures/boqu2/wallsp3_gloss.tga
rm textures/boqu2/whitetrim7_norm.tga
rm textures/boqu2/blueblacktrim.tga
rm textures/boqu2/squaretilewhite_gloss.tga
rm textures/boqu2/darkpanel.tga
rm textures/boqu2/floorplates2.tga
rm textures/boqu2/concrete4.tga
rm textures/boqu2/floorplates.tga
rm textures/boqu2/brighttechpanel_norm.tga
rm textures/boqu2/vent4_gloss.tga
rm textures/exwsw/eX_trim_psimple_07_blue.tga
# textures/exwsw/eX_surf_metallightgrey.tga
rm textures/exwsw/eX_trim_psimple_06_gloss.tga
rm textures/exwsw/eX_mtl_panel_03b.ktx
rm textures/exwsw/eX_trim_psimple_04_gloss.tga
rm textures/exwsw/trim_red_gloss.tga
rm textures/exwsw/eX_q2_01d_norm.jpg
rm textures/exwsw/eX_surf_metalgreen_norm.tga
rm textures/exwsw/eX_q2_01e_daze_tri.jpg
# textures/exwsw/eX_trim_psimple_07_red.ktx
rm textures/exwsw/eX_wall_01.ktx
rm textures/exwsw/eX_wall_bigrib_02c_gloss.tga
rm textures/exwsw/eX_surf_metalgreen_gloss.tga
rm textures/exwsw/eX_mtl_panel_02_norm.tga
rm textures/exwsw/eX_wall_bplate_06.ktx
rm textures/exwsw/eX_trim_vert_01_brown.tga
# textures/exwsw/eX_rplates_01_daze_gloss.tga
# textures/exwsw/eX_mtl_panel_04_norm.tga
rm textures/exwsw/eX_q2_01d_daze.jpg
rm textures/exwsw/eX_trim_simple_01_gloss.tga
rm textures/exwsw/eXmetalFloor02.tga
rm textures/exwsw/eX_wall_bigrib_02b_gloss.tga
# textures/exwsw/eX_surf_metaldarkgrey_gloss.tga
# textures/exwsw/eX_trim_psimple_04_norm.tga
rm textures/exwsw/eX_metalplate_01_norm.tga
rm textures/exwsw/eX_trim_psimple_05_straight.ktx
rm textures/exwsw/eX_wall_01_big_gloss.tga
rm textures/exwsw/eX_wall_bplate_06_norm.tga
rm textures/exwsw/eX_trim_vert_01_norm.tga
rm textures/exwsw/eX_wall_01_big_green_gloss.tga
rm textures/exwsw/eX_mtl_panel_02.ktx
rm textures/exwsw/eX_wall_bigrib_02c.ktx
rm textures/exwsw/eX_wall_panel_05_norm.tga
rm textures/exwsw/eX_mtl_panel_04.ktx
rm textures/exwsw/eX_wall_b01_gloss.tga
rm textures/exwsw/eXmetal_plate01c.ktx
rm textures/exwsw/eX_trim_vert_01.tga
rm textures/exwsw/eX_wall_01_big_green2_gloss.tga
# textures/exwsw/eX_mtl_panel_04_daze_gloss.tga
rm textures/exwsw/eX_q2_01e_gloss.tga
rm textures/exwsw/trim_red_2_norm.tga
rm textures/exwsw/eX_trim_support_03_thin_norm.tga
rm textures/exwsw/eX_trim_simple_01.ktx
rm textures/exwsw/eX_wall_panels_gloss.tga
rm textures/exwsw/eX_wall_panels_08_norm.tga
rm textures/exwsw/eX_trim_baseboard_blue_concrete.tga
# textures/exwsw/eX_mtl_panel_03_gloss.tga
rm textures/exwsw/eX_trim_psimple_07_blue.ktx
# textures/exwsw/eXmetalrib01_green.tga
rm textures/exwsw/eX_trim_psimple_05.ktx
rm textures/exwsw/eX_deswall_01_daze.ktx
# textures/exwsw/eXmetalrib01_blue.tga
rm textures/exwsw/eX_trim_support_03_thin.tga
rm textures/exwsw/eXmetalFloor02_norm.tga
rm textures/exwsw/eX_trim_psimple_05_norm.tga
# textures/exwsw/eX_mtl_panel_03b_gloss.tga
rm textures/exwsw/eX_wall_panels.ktx
rm textures/exwsw/eX_wall_01_big_green2_norm.tga
rm textures/exwsw/eX_wall_panels_norm.tga
rm textures/exwsw/eX_mtl_panel_03c.ktx
# textures/exwsw/eX_wall_01_norm.tga
rm textures/exwsw/eX_wall_b01.ktx
rm textures/exwsw/eX_q2_01.ktx
rm textures/exwsw/eX_trim_baseboard.tga
rm textures/exwsw/eX_trim_simple03_norm.tga
rm textures/exwsw/eX_wall_b01_norm.tga
rm textures/exwsw/eX_wall_u207_gloss.tga
rm textures/exwsw/eX_trim_psimple_06.ktx
rm textures/exwsw/eX_trim_psimple_05_gloss.tga
# textures/exwsw/eXmetalrib01_red.tga
rm textures/exwsw/eX_wall_01_big_green_norm.tga
# textures/exwsw/eX_surf_metalbrown.ktx
rm textures/exwsw/eX_trim_01.tga
rm textures/exwsw/eX_trim_support_03.tga
rm textures/exwsw/eX_wall_01_big_green2.tga
# textures/exwsw/eX_mtl_bigplate_04b_daze_gloss.tga
rm textures/exwsw/eX_trim_psimple_05_straight_white.ktx
rm textures/exwsw/eX_wall_bigrib_02b_norm.tga
rm textures/exwsw/eX_mtl_panel_04_gloss.tga
rm textures/exwsw/eX_wall_bigrib_02_gloss.tga
rm textures/exwsw/eX_trim_psimple_07.ktx
rm textures/exwsw/eX_trim_baseboard_norm.tga
rm textures/exwsw/eX_wall_panels_08.ktx
rm textures/exwsw/eX_metalwall02.ktx
# textures/exwsw/eX_q2_01e_daze.jpg
rm textures/exwsw/eXmetal_plate01B_norm.tga
rm textures/exwsw/eX_trim_baseboard_blue.tga
rm textures/exwsw/eX_trim_support_03_thin_gloss.tga
rm textures/exwsw/trim_red_norm.tga
rm textures/exwsw/eX_rplates_01_gloss.tga
rm textures/exwsw/eX_mtl_panel_03c_gloss.tga
rm textures/exwsw/eX_q2_01c.ktx
rm textures/exwsw/eX_mtl_panel_03.ktx
# textures/exwsw/eX_surf_metal_gloss.tga
rm textures/exwsw/eX_trim_baseboard_blue_concrete_norm.tga
rm textures/exwsw/eX_deswall_01_daze_gloss.tga
rm textures/exwsw/eX_trim_01_norm.tga
# textures/exwsw/eX_q2_01e_daze_gloss.tga
rm textures/exwsw/eX_trim_psimple_05_straight_gloss.tga
# textures/exwsw/eX_metalSupp01_blue_gloss.ktx
rm textures/exwsw/eX_trim_support_03_norm.tga
rm textures/exwsw/eX_q2_01c_gloss.tga
rm textures/exwsw/eX_trim_simple03_brown.ktx
rm textures/exwsw/eX_q2_01e_daze_tri_norm.jpg
rm textures/exwsw/eX_wall_bigrib_02b.ktx
rm textures/exwsw/eX_trim_baseboard_02.ktx
rm textures/exwsw/eX_surf_metalgreen.tga
rm textures/exwsw/eX_trim_baseboard_03.ktx
rm textures/exwsw/eX_wall_bigrib_02_norm.tga
# textures/exwsw/eX_metalSupp01_norm.tga
# textures/exwsw/eX_mtl_bigplate_04b_daze.jpg
rm textures/exwsw/eX_metalSupp01.ktx
rm textures/exwsw/eX_wall_panel_05.ktx
# textures/exwsw/eX_rplates_01_daze.jpg
rm textures/exwsw/eX_q2_01d_daze_gloss.tga
rm textures/exwsw/eXmetal_plate01B_gloss.tga
rm textures/exwsw/eX_deswall_01_gloss.tga
# textures/exwsw/eX_surf_norm.tga
rm textures/exwsw/eXmetalrib01.tga
rm textures/exwsw/eX_trim_vert_01_gloss.tga
# textures/exwsw/eX_surf_metalorange.ktx
# textures/exwsw/eX_rplates_01_norm.tga
rm textures/exwsw/eX_trim_support_03_gloss.tga
rm textures/exwsw/eX_trim_simple03_gloss.tga
rm textures/exwsw/eXmetal_plate01c_norm.tga
rm textures/exwsw/eX_deswall_01_orange.ktx
rm textures/exwsw/eX_rplates_01.tga
rm textures/exwsw/eX_trim_psimple_05_straight_green.ktx
rm textures/exwsw/trim_red_2.tga
rm textures/exwsw/trim_red_2_gloss.tga
rm textures/exwsw/eXmetal_plate01c_gloss.tga
rm textures/exwsw/eX_trim_psimple_05_straight_blue.ktx
rm textures/exwsw/eX_metalwall02_norm.tga
# textures/exwsw/eXmetalrib01_norm.tga
rm textures/exwsw/eX_mtl_panel_03c_norm.tga
rm textures/exwsw/eX_wall_panels_08_gloss.tga
# textures/exwsw/eX_trim_psimple_07_norm.tga
rm textures/exwsw/eX_q2_01e_daze_tri_gloss.tga
rm textures/exwsw/eX_q2_01d_gloss.tga
# textures/exwsw/eX_q2_01e_norm.jpg
# textures/exwsw/eX_mtl_panel_03b_norm.tga
# textures/exwsw/eX_q2_01_daze.jpg
rm textures/exwsw/trim_red.tga
rm textures/exwsw/eX_deswall_01_norm.tga
rm textures/exwsw/eX_q2_01c_norm.jpg
rm textures/exwsw/eX_trim_baseboard_blue_concrete_gloss.tga
rm textures/exwsw/eX_trim_baseboard_03_norm.tga
# textures/exwsw/eX_mtl_panel_03_norm.tga
# textures/exwsw/eX_wall_01_brown.ktx
rm textures/exwsw/eX_wall_bigrib_02c_norm.tga
rm textures/exwsw/eX_mtl_bigplate_04b.jpg
rm textures/exwsw/eX_trim_psimple_05_straight_red.ktx
rm textures/exwsw/eX_mtl_bigplate_04_gloss.tga
rm textures/exwsw/eX_metalplate_01_gloss.tga
rm textures/exwsw/eX_metalplate_01.ktx
rm textures/exwsw/eX_trim_baseboard_03_gloss.tga
rm textures/exwsw/eX_wall_01_big_green.tga
# textures/exwsw/eX_surf_metaldarkgrey.ktx
rm textures/exwsw/eX_wall_bigrib_02.tga
rm textures/exwsw/eX_q2_01b_norm.tga
# textures/exwsw/eX_q2_01_daze_gloss.tga
rm textures/exwsw/eX_wall_01_big.ktx
rm textures/exwsw/eX_deswall_01.ktx
rm textures/exwsw/eX_wall_bplate_06_gloss.tga
rm textures/exwsw/eX_q2_01d.jpg
rm textures/exwsw/eX_q2_01b.ktx
rm textures/exwsw/eX_trim_baseboard_gloss.tga
# textures/exwsw/eX_mtl_panel_brown_03b.ktx
rm textures/exwsw/eX_wall_u207_norm.tga
# textures/exwsw/eX_metalSupp01_blue.tga
rm textures/exwsw/eX_wall_u207.ktx
rm textures/exwsw/eX_trim_psimple_05_straight_norm.tga
rm textures/exwsw/eX_trim_simple03.ktx
# textures/exwsw/eX_q2_01_norm.tga
rm textures/exwsw/eX_trim_baseboard_02_gloss.tga
rm textures/exwsw/eX_trim_01_gloss.tga
rm textures/exwsw/eXmetal_plate01B.ktx
# textures/exwsw/eX_trim_psimple_04.ktx
rm textures/exwsw/eX_trim_simple_01_norm.tga
rm textures/exwsw/eX_q2_01e.jpg
rm textures/exwsw/eX_mtl_bigplate_04_norm.tga
# textures/exwsw/eX_mtl_bigplate_04b_norm.jpg
# textures/exwsw/eX_trim_psimple_07_gloss.tga
rm textures/exwsw/eX_wall_panel_05_gloss.tga
rm textures/exwsw/eX_metalSupp01_gloss.tga
rm textures/exwsw/eX_wall_01_big_norm.tga
rm textures/exwsw/eX_q2_01b_gloss.tga
# textures/exwsw/eX_mtl_panel_04_daze.ktx
# textures/exwsw/eX_mtl_panel_brown_03.ktx
rm textures/exwsw/eX_trim_psimple_06_norm.tga
rm textures/exwsw/eXmetalFloor02_gloss.tga
rm textures/exwsw/eX_q2_01_gloss.tga
rm textures/exwsw/eX_mtl_panel_02_gloss.tga
# textures/exwsw/eXmetalrib01_gloss.tga
rm textures/exwsw/eX_metalwall02_gloss.tga
rm textures/exwsw/eX_mtl_bigplate_04b_gloss.tga
rm textures/exwsw/eX_mtl_bigplate_04.ktx
# textures/exwsw/eX_wall_01_gloss.tga
rm textures/exwsw/eX_trim_baseboard_02_norm.tga
rm textures/blx_ca/blx_ca_light.tga
rm textures/blx_ca/blx_ca_light_square.tga
rm textures/blx_ca/blx_ca_light_short.tga
rm textures/lights/trim2_norm.tga
rm textures/lights/purepurple.tga
rm textures/lights/turqs2_gloss.tga
rm textures/lights/trim06_gloss.tga
rm textures/lights/strip.tga
rm textures/lights/pureyellow2.tga
rm textures/lights/gridl01.tga
rm textures/lights/stripred.blend.tga
rm textures/lights/neon2s.tga
rm textures/lights/01neutrem.tga
rm textures/lights/tech.blend.tga
rm textures/lights/strip_gloss.tga
# textures/lights/01neutres.tga
# textures/lights/square_light_tile.tga
rm textures/lights/oc2.blend.tga
rm textures/lights/trim06.blend.tga
rm textures/lights/trim06.tga
rm textures/lights/strippurple.blend.tga
rm textures/lights/01bluem.tga
rm textures/lights/blue1.tga
# textures/lights/01neutrel.tga
rm textures/lights/oc1.tga
rm textures/lights/tech.tga
rm textures/lights/turqs2.tga
rm textures/lights/tech_norm.tga
rm textures/lights/turqs2_norm.tga
rm textures/lights/pureyellow.tga
rm textures/lights/strip.blend.tga
# textures/lights/panel1.tga
# textures/lights/blacktrim01.tga
rm textures/lights/trim04.tga
rm textures/lights/oc1_gloss.tga
rm textures/lights/trim03.blend.tga
# textures/lights/phonograph.tga
rm textures/lights/stripblue.blend.tga
rm textures/lights/blacktrim02.tga
rm textures/lights/trim03_gloss.tga
rm textures/lights/trim05_gloss.tga
rm textures/lights/oc2.tga
rm textures/lights/strip_norm.tga
rm textures/lights/trim2.blend.tga
rm textures/lights/trim03_norm.tga
rm textures/lights/stripgreen.blend.tga
# textures/lights/turqs1.tga
rm textures/lights/trim05.tga
rm textures/lights/trim06_norm.tga
rm textures/lights/neonlamp.tga
rm textures/lights/trim04_norm.tga
rm textures/lights/trim05_norm.tga
# textures/lights/01bluel.tga
rm textures/lights/trim2_gloss.tga
rm textures/lights/puregreen.tga
rm textures/lights/stripcyan.blend.tga
rm textures/lights/striporange.blend.tga
rm textures/lights/bluetrim.tga
rm textures/lights/bluetrim2.tga
rm textures/lights/pureorange2.tga
rm textures/lights/turqs2.blend.tga
rm textures/lights/pureorange.tga
rm textures/lights/trim03.tga
rm textures/lights/neon2s.blend.tga
# textures/lights/turqs1.blend.tga
rm textures/lights/purple1.tga
rm textures/lights/turqs1_gloss.tga
# textures/lights/bright2.tga
# textures/lights/bright1.tga
rm textures/lights/glowtrim.blend.tga
rm textures/lights/stripyellow.blend.tga
rm textures/lights/bluetrim3.tga
rm textures/lights/trim2.tga
# textures/lights/oc3.tga
rm textures/lights/icelight.tga
rm textures/lights/bluetrim4.tga
rm textures/lights/trim04.blend.tga
rm textures/lights/turqs1_norm.tga
# textures/lights/01blues.tga
rm textures/lights/trim04_gloss.tga
# textures/lights/purewhite.tga
rm textures/lights/glowtrim.tga
rm textures/lights/oc1_norm.tga
rm textures/lights/neonlamp.blend.tga
rm textures/lights/purered2.tga
rm textures/lights/trim05.blend.tga
rm textures/lights/oc2_norm.tga
rm textures/lights/purered3.tga
rm textures/lights/purered.tga
rm textures/lights/oc2_focus.tga
# textures/cocaine/lazery_green.jpg
# textures/cocaine/lazery_blue.jpg
# textures/cocaine/lazery_white.jpg
# textures/cocaine/lazery_orange.jpg
# textures/cocaine/lazery_kush.jpg
# textures/cocaine/lazery_red.jpg
rm textures/scifi_interior/aluminium_panel2_blue.tga
rm textures/scifi_interior/aluminium_panel2_orange.tga
rm textures/scifi_interior/floortile2_norm.tga
rm textures/scifi_interior/metal_panel_norm.tga
rm textures/scifi_interior/aluminium_trim_orange.tga
rm textures/scifi_interior/orange_panel_gloss.tga
rm textures/scifi_interior/aluminium_clean_norm.tga
rm textures/scifi_interior/decal_comptext1.tga
rm textures/scifi_interior/decal_arrow_orange.tga
rm textures/scifi_interior/grid_norm.tga
rm textures/scifi_interior/floortile.tga
rm textures/scifi_interior/gloss_shiny.tga
rm textures/scifi_interior/grid_orange_norm.tga
rm textures/scifi_interior/floortile_norm.tga
rm textures/scifi_interior/orange_panel.tga
rm textures/scifi_interior/aluminium_panel4.tga
rm textures/scifi_interior/baseblue.tga
rm textures/scifi_interior/rigged_panel1_norm.tga
rm textures/scifi_interior/wallmetal_orange.tga
rm textures/scifi_interior/floorpanel_norm.tga
rm textures/scifi_interior/floorpanel_black.tga
rm textures/scifi_interior/basechrome.tga
rm textures/scifi_interior/rigged_panel1_white.tga
rm textures/scifi_interior/noise.tga
rm textures/scifi_interior/glass_gloss.tga
rm textures/scifi_interior/grid_blue_norm.tga
rm textures/scifi_interior/aluminium_panel_norm.tga
rm textures/scifi_interior/flatnorm.tga
rm textures/scifi_interior/aluminium_panel_small2.tga
rm textures/scifi_interior/floorpanel.tga
rm textures/scifi_interior/aluminium_panel_small_orange.tga
rm textures/scifi_interior/metal_panel_gloss.tga
rm textures/scifi_interior/metal_panel.tga
rm textures/scifi_interior/aluminium_panel2_norm.tga
rm textures/scifi_interior/scanline_red.tga
rm textures/scifi_interior/aluminium_panel.tga
rm textures/scifi_interior/basered.tga
rm textures/scifi_interior/aluminium_panel_small_norm.tga
rm textures/scifi_interior/decal_up_grey.tga
rm textures/scifi_interior/baseblack.tga
rm textures/scifi_interior/grid_orange.tga
rm textures/scifi_interior/aluminium_trim_norm.tga
rm textures/scifi_interior/wallmetal_grey.tga
rm textures/scifi_interior/orange_panel_norm.tga
rm textures/scifi_interior/aluminium_panel_small.tga
rm textures/scifi_interior/covenant2.ktx
rm textures/scifi_interior/basesilver.tga
rm textures/scifi_interior/aluminium_airvent.tga
rm textures/scifi_interior/01.ktx
rm textures/scifi_interior/aluminium_airvent_norm.tga
rm textures/scifi_interior/03.ktx
rm textures/scifi_interior/aluminium_trim_white.tga
rm textures/scifi_interior/button_unlocked.tga
rm textures/scifi_interior/covenant1.ktx
rm textures/scifi_interior/aluminium_trim_clean.tga
rm textures/scifi_interior/glass.tga
rm textures/scifi_interior/decal_up_orange.tga
rm textures/scifi_interior/aluminium_airvent_gloss.tga
rm textures/scifi_interior/decal_comptext2.tga
rm textures/scifi_interior/basewhite.tga
rm textures/scifi_interior/02.ktx
rm textures/scifi_interior/scanline_green.tga
rm textures/scifi_interior/rigged_panel1_gloss.tga
rm textures/scifi_interior/aluminium_panel_blue.tga
rm textures/scifi_interior/aluminium_panel2.tga
rm textures/scifi_interior/grid.tga
rm textures/scifi_interior/blue_glass.tga
rm textures/scifi_interior/aluminium_trim_clean_norm.tga
rm textures/scifi_interior/rigged_panel1.tga
rm textures/scifi_interior/orange_panel2_norm.tga
rm textures/scifi_interior/orange_panel2_gloss.tga
rm textures/scifi_interior/aluminium_panel_orange.tga
rm textures/scifi_interior/rollupmetal.tga
rm textures/scifi_interior/aluminium_trim_black.tga
rm textures/scifi_interior/decal_comptext3.tga
rm textures/scifi_interior/metal_panel_darkblue.tga
rm textures/scifi_interior/glass_effect.tga
rm textures/scifi_interior/gloss.tga
rm textures/scifi_interior/button_locked.tga
rm textures/scifi_interior/floortile2.tga
rm textures/scifi_interior/orange_panel2.tga
rm textures/scifi_interior/grid_blue.tga
rm textures/scifi_interior/aluminium_panel3.tga
rm textures/scifi_interior/glass_normal.tga
rm textures/scifi_interior/aluminium_clean.tga
rm textures/scifi_interior/aluminium_panel_small_blue.tga
rm textures/scifi_interior/rollupmetal_norm.tga
rm textures/scifi_interior/baseorange.tga
rm textures/scifi_interior/wallmetal_blue.tga
rm textures/jewels/neon_light_bg.tga
rm textures/jewels/jumppad_dot.tga
rm textures/jewels/neon_blue.tga
rm textures/jewels/jumppad_strip.tga
rm textures/jewels/neon_red.tga
rm textures/jewels/neon_alpha.tga
rm textures/melee/pure002.tga
rm textures/melee/pure001.tga
rm textures/melee/emptyness.tga
rm textures/melee/pure001_fx0.tga
# textures/natestah/nateswater.tga
rm textures/natestah/nateweb.tga
rm textures/zone_neutre/beige_contour01.tga
rm textures/zone_neutre/skyblue.tga
rm textures/zone_neutre/beige.tga
rm textures/zone_neutre/beige_dark.tga
rm textures/zone_neutre/beige_fleche01.tga
rm textures/zone_neutre/orange_contour01.tga
rm textures/zone_neutre/beige_fleche01_glow.jpg
# textures/metal/treadplate0015f.tga
rm textures/metal/orangewall_double_norm.tga
# textures/metal/treadplate0015_gloss.tga
# textures/metal/treadplate0015b.tga
# textures/metal/treadplate0015.tga
rm textures/metal/redwall_norm.tga
rm textures/metal/orangewall_norm.tga
rm textures/metal/orangewall_single_gloss.tga
rm textures/metal/orangewall_x4_norm.tga
rm textures/metal/redwall_single.ktx
# textures/metal/metalbaseyellow0033dirt.ktx
rm textures/metal/redwall_x4_norm.tga
rm textures/metal/bigtreadplateg_gloss.tga
rm textures/metal/treadplate0015e.tga
rm textures/metal/orangewall_gloss.tga
# textures/metal/aluminium_gloss.tga
# textures/metal/treadplate0015d.tga
# textures/metal/metalbaseyellow0033_gloss.tga
rm textures/metal/orangewall_x4_gloss.tga
# textures/metal/bigtreadplateg.tga
rm textures/metal/orangewall.ktx
rm textures/metal/redmetalbase_gloss.tga
# textures/metal/chrome.blend.tga
rm textures/metal/redwall_double_gloss.tga
rm textures/metal/treadplate0015c.tga
rm textures/metal/redwall_single_norm.tga
# textures/metal/aluminium.tga
rm textures/metal/redwall_single_gloss.tga
# textures/metal/treadplate0015g.tga
# textures/metal/treadplate0015_norm.tga
rm textures/metal/metalbulk_norm.tga
# textures/metal/metalbaseyellow0033.ktx
rm textures/metal/redwall_gloss.tga
rm textures/metal/bigtreadplateg_norm.tga
rm textures/metal/chrome.tga
rm textures/metal/redwall_double.ktx
rm textures/metal/metalbulk_gloss.ktx
rm textures/metal/redmetalbase_norm.tga
rm textures/metal/orangewall_x4.ktx
# textures/metal/treadplate0015f_gloss.ktx
rm textures/metal/redwall_x4.ktx
rm textures/metal/orangewall_single_norm.tga
rm textures/metal/redwall_x4_gloss.tga
# textures/metal/metalbaseyellow0033dirt_gloss.tga
rm textures/metal/orangewall_double.ktx
# textures/metal/redmetalbase.ktx
rm textures/metal/redwall_double_norm.tga
rm textures/metal/redwall.ktx
rm textures/metal/orangewall_double_gloss.tga
rm textures/metal/metalbulk.tga
rm textures/metal/orangewall_single.ktx
rm textures/neon/jusco_supermarket_purple.tga
rm textures/neon/neon_square2.tga
rm textures/neon/round_sign.tga
rm textures/neon/neon_square.tga
rm textures/neon/jujitsu_sign4.tga
rm textures/neon/jujitsu_sign3.tga
rm textures/neon/playwarsow.tga
rm textures/neon/basskick4.jpg
rm textures/neon/basskick3.jpg
rm textures/neon/round_sign_purple.tga
rm textures/neon/jujitsu_sign1.tga
rm textures/neon/wsw_kanji_orange.tga
rm textures/neon/jusco_supermarket_yellow.tga
rm textures/neon/basskick1.jpg
rm textures/neon/jujitsu_sign5.tga
rm textures/neon/bosobosou_sign.tga
rm textures/neon/basskick2.jpg
rm textures/neon/jujitsu_sign2.tga
rm textures/boqu/bigfloor.ktx
rm textures/boqu/simplemid2.tga
rm textures/boqu/tile_slim_yellow5.tga
rm textures/boqu/whitepanels4_gloss.tga
rm textures/boqu/ventonly.tga
rm textures/boqu/metalpanel4.tga
rm textures/boqu/whitedoublepanel_gloss.tga
rm textures/boqu/greytrim_yellow_norm.tga
rm textures/boqu/lightstripe_blue.tga
rm textures/boqu/simplelight.tga
rm textures/boqu/testbox.tga
rm textures/boqu/stairfront_light_glow.tga
rm textures/boqu/door1_gloss.tga
rm textures/boqu/treadplate_norm.tga
rm textures/boqu/tile_slim.tga
rm textures/boqu/hexa_lamp_glow.tga
rm textures/boqu/wallbase2_gloss.tga
rm textures/boqu/biglightfloor.ktx
rm textures/boqu/door1_norm.tga
rm textures/boqu/hexagon_floor.tga
rm textures/boqu/yellow_pillar2.tga
rm textures/boqu/light2.tga
rm textures/boqu/ceilinglamptrim_orange.tga
rm textures/boqu/teleporterback.tga
rm textures/boqu/simplestripe.tga
rm textures/boqu/cables2.tga
rm textures/boqu/tile_slim_norm.tga
rm textures/boqu/lighttrimwide.tga
rm textures/boqu/whitepanels.tga
rm textures/boqu/greytrim_blank.tga
rm textures/boqu/whitepanel5.tga
rm textures/boqu/floor_tiles.tga
rm textures/boqu/darkgrey_hexpattern_gloss.tga
rm textures/boqu/lightstripe_blue_glow.tga
rm textures/boqu/squarelamp_blue.tga
rm textures/boqu/light_concrete2_norm.tga
rm textures/boqu/ventonly_gloss.tga
rm textures/boqu/bigtiles_norm.tga
rm textures/boqu/midtrim_2_w.tga
rm textures/boqu/grytrimtop2_normal.tga
rm textures/boqu/simpledark2_gloss.tga
rm textures/boqu/tile_whiteglow_norm.tga
rm textures/boqu/door.tga
rm textures/boqu/wallbottom2_norm.tga
rm textures/boqu/stairtop_gloss.tga
rm textures/boqu/redpanels.ktx
rm textures/boqu/yellow_pillar5_gloss.tga
rm textures/boqu/factorytrim2_gloss.tga
rm textures/boqu/floorslim_plate.tga
rm textures/boqu/metalpanel.tga
rm textures/boqu/midtrim_2.tga
rm textures/boqu/squarelamp_glow.tga
rm textures/boqu/roundlighttile.tga
rm textures/boqu/simpledark_grate_gloss.tga
rm textures/boqu/light1_norm.tga
rm textures/boqu/whitepanel01.tga
rm textures/boqu/metaltrim_gloss.tga
rm textures/boqu/hexa_lamp_gloss.tga
rm textures/boqu/g256_orange.tga
rm textures/boqu/greytrim2x.tga
rm textures/boqu/greytiles.tga
rm textures/boqu/tile_slim_light_glow.tga
rm textures/boqu/lightstripe.tga
rm textures/boqu/whitepanel2_norm.tga
rm textures/boqu/boqu_window.tga
rm textures/boqu/wallbase_gloss.tga
rm textures/boqu/greytrim2x_norm.tga
rm textures/boqu/light1.tga
rm textures/boqu/gratetrim_norm,tga.tga
rm textures/boqu/darkgrey_hexpattern_norm.tga
rm textures/boqu/bright_metalhex.tga
rm textures/boqu/factorytrim.tga
rm textures/boqu/roundlighttile_gloss.tga
rm textures/boqu/vent2.tga
rm textures/boqu/hex_grate_2norm.tga
rm textures/boqu/yellowtrim1_norm.tga
rm textures/boqu/factorytrim2.tga
rm textures/boqu/fusebox_norm.tga
rm textures/boqu/squarelamp_norm.tga
rm textures/boqu/whitepanels4_norm.tga
rm textures/boqu/simpledark_gloss.tga
rm textures/boqu/simplemid.tga
rm textures/boqu/yellow_pillar2_gloss.tga
rm textures/boqu/midtrim_2_glow.tga
rm textures/boqu/bigwhitetiles2_gloss.tga
rm textures/boqu/stairfront.tga
rm textures/boqu/wallbase2_norm.tga
rm textures/boqu/greytrim_grate_gloss.tga
rm textures/boqu/whitepanel01_gloss.tga
rm textures/boqu/light_concrete1.ktx
rm textures/boqu/rect_lamp_gloss.tga
rm textures/boqu/greytrim7_gloss.tga
rm textures/boqu/hexagon_floor2_xxnorm.tga
rm textures/boqu/yellow_trim6_norm.tga
rm textures/boqu/hexagon_floor_normal.tga
rm textures/boqu/simpledark_grate.tga
rm textures/boqu/stairfront_light.tga
rm textures/boqu/tile_slim_yellow2.tga
rm textures/boqu/whitepanel01_norm.tga
rm textures/boqu/yellow_pillar3_gloss.tga
rm textures/boqu/hexx_norm.tga
rm textures/boqu/lamppanel_gloss.tga
rm textures/boqu/greytrim_yellow.tga
rm textures/boqu/lamppanel_norm.tga
rm textures/boqu/midtrim_glow.tga
rm textures/boqu/vent2_norm.tga
rm textures/boqu/ceilingtile.tga
rm textures/boqu/floorpanels_yellowstrip.tga
rm textures/boqu/floor_tiles_norm.tga
rm textures/boqu/whitedoublepanel.tga
rm textures/boqu/ventonly_norm.tga
rm textures/boqu/med_concrete_cnorm.tga
rm textures/boqu/wallbase_norm.tga
rm textures/boqu/ceilinglamptrim_pink.tga
rm textures/boqu/hexagon_floor_gloss.tga
rm textures/boqu/tile_slim_light_yellow_glow.tga
rm textures/boqu/ceilingtile_norm.tga
rm textures/boqu/simpledark2_norm.tga
rm textures/boqu/biglightfloor_glow.tga
rm textures/boqu/testbox_gloss.tga
rm textures/boqu/floorpanel_grate_gloss.tga
rm textures/boqu/door1.ktx
rm textures/boqu/whitepanel2_gloss.tga
rm textures/boqu/simplelight2.tga
rm textures/boqu/midtrim_pink_glow.tga
rm textures/boqu/greytrim_grate_norm.tga
rm textures/boqu/gratetrim_norm.tga
rm textures/boqu/metalpanel3_gloss.tga
rm textures/boqu/fusebox_front_norm.tga
rm textures/boqu/floorpanels_yellowstrip_norm.tga
rm textures/boqu/greytrim_hexyellow_gloss.tga
rm textures/boqu/hexa_lamp_norm.tga
rm textures/boqu/med_con_norm.tga
rm textures/boqu/lighttrimwide_norm.tga
rm textures/boqu/ceilinglamptrim.tga
rm textures/boqu/floorpanel_grate_norm.tga
rm textures/boqu/midtrim_2_w_glow.tga
rm textures/boqu/tile_slim_gloss.tga
rm textures/boqu/vent2_gloss.tga
rm textures/boqu/floor_tiles_gloss.tga
rm textures/boqu/midtrim_yellow.tga
rm textures/boqu/ceilinglamp_w_glow.tga
rm textures/boqu/treadplate_yellow.tga
rm textures/boqu/treadplate_norml.tga
rm textures/boqu/techtile1_norm.tga
rm textures/boqu/light2_norm.tga
rm textures/boqu/yellowtrim1.tga
rm textures/boqu/tile_slim_yellow4.tga
rm textures/boqu/vent_gloss.tga
rm textures/boqu/floorpanel_grate.tga
rm textures/boqu/tile_slim_light_norm.tga
rm textures/boqu/ceilinglamptrim_orange_glow.tga
rm textures/boqu/tile_slim_yellow1.tga
rm textures/boqu/bright_metal_gloss.tga
rm textures/boqu/white_panel1.tga
rm textures/boqu/lamppanel3.tga
rm textures/boqu/gratetrim_gloss.tga
rm textures/boqu/midtrim_pink.tga
rm textures/boqu/white_panel1_gloss.tga
rm textures/boqu/teleporterfront_gloss.tga
rm textures/boqu/hexagon_floor2.tga
rm textures/boqu/greytrimtop_norm .tga
rm textures/boqu/tile_slim_light.tga
rm textures/boqu/yellow_pillar2_norm.tga
rm textures/boqu/med_concrete2.tga
rm textures/boqu/med_concrete2_norm.tga
rm textures/boqu/ceilinglamp_w.tga
rm textures/boqu/white_panel1_norm.tga
rm textures/boqu/greytrim.tga
rm textures/boqu/whitepanels-Recovered.tga
rm textures/boqu/teleporterfront_norm.tga
rm textures/boqu/greytrimtop.tga
rm textures/boqu/fusebox_front.tga
rm textures/boqu/greytiles_norm.tga
rm textures/boqu/panel_norm.tga
rm textures/boqu/light_concrete2_gloss.tga
rm textures/boqu/bright_metal_norm.tga
rm textures/boqu/light_concrete1_gloss.tga
rm textures/boqu/whitepanel5_norm.tga
rm textures/boqu/metalpanel4_gloss.tga
rm textures/boqu/fusebox_front_gloss.tga
rm textures/boqu/yellow_pillar5.tga
rm textures/boqu/simpledark_grate_norm.tga
rm textures/boqu/redpanels_gloss.tga
rm textures/boqu/lamppanel_glow.tga
rm textures/boqu/cables.tga
rm textures/boqu/biglightfloor_norm.tga
rm textures/boqu/hex_grate_gloss.tga
rm textures/boqu/metaltrim.tga
rm textures/boqu/metaltrim_norm.tga
rm textures/boqu/tile_norm.tga
rm textures/boqu/factorytrim2_norm.tga
rm textures/boqu/tile_slim_light_yellow.tga
rm textures/boqu/gratepanel.tga
rm textures/boqu/redpanels_norm.tga
rm textures/boqu/tile_slim_yellow3.tga
rm textures/boqu/midtrim_blue.tga
rm textures/boqu/vent_norm.tga
rm textures/boqu/med_concrete2_gloss.tga
rm textures/boqu/decals/tele_decal1.tga
rm textures/boqu/decals/whiteventdecal2_gloss.tga
rm textures/boqu/decals/explosive_decal.tga
rm textures/boqu/decals/whiteventdecal_norm.tga
rm textures/boqu/decals/vent1.tga
rm textures/boqu/decals/vent1_gloss.tga
rm textures/boqu/decals/tele_decal2_blue.tga
rm textures/boqu/decals/holohealth.tga
rm textures/boqu/decals/yellowarrows_outlined.tga
rm textures/boqu/decals/whiteventdecal_gloss.tga
rm textures/boqu/decals/wswdecal.tga
rm textures/boqu/decals/whiteventdecal.tga
rm textures/boqu/decals/whiteventdecal2.tga
rm textures/boqu/decals/vent1_norm.tga
rm textures/boqu/decals/tele_decal1_blue.tga
rm textures/boqu/decals/holo1.tga
rm textures/boqu/decals/whiteventdecal2_norm.tga
rm textures/boqu/testbox_norm.tga
rm textures/boqu/panel_gloss.tga
rm textures/boqu/yellow_pillar5_norm.tga
rm textures/boqu/tile_whiteglow.tga
rm textures/boqu/wallbase.tga
rm textures/boqu/rect_lamp.ktx
rm textures/boqu/door_gloss.tga
rm textures/boqu/metal_brushed_norm.tga
rm textures/boqu/lamppanel3_glow.tga
rm textures/boqu/bigtiles_gloss.tga
rm textures/boqu/greytrim_grate.tga
rm textures/boqu/cables_gloss.tga
rm textures/boqu/hex_grate_xxnorm.tga
rm textures/boqu/midtrim_yellow_glow.tga
rm textures/boqu/glow_halo_yellow.tga
rm textures/boqu/bright_metalhex_gloss.tga
rm textures/boqu/teleporterfront.tga
rm textures/boqu/cables2_gloss.tga
rm textures/boqu/greytrimtop_gloss.tga
rm textures/boqu/lightstripe_norm.tga
rm textures/boqu/tread_norm2.tga
rm textures/boqu/cables2_norm.tga
rm textures/boqu/gratepanel_norm.tga
rm textures/boqu/greytrim_blank_gloss.tga
rm textures/boqu/hexagon_floor2_gloss.tga
rm textures/boqu/stairfront_gloss.tga
rm textures/boqu/ceilinglamptrim_gloss.tga
rm textures/boqu/tile_slim_light_gloss.tga
rm textures/boqu/darkgreynoise.tga
rm textures/boqu/lamppanel.tga
rm textures/boqu/rect_lamp_glow.tga
rm textures/boqu/warsow_neon_gold2.tga
rm textures/boqu/bigwhitetiles2_norm.tga
rm textures/boqu/floorslim_plate_gloss.tga
rm textures/boqu/treadplate.tga
rm textures/boqu/ceilingtile_gloss.tga
rm textures/boqu/ceilinglamptrim_norm.tga
rm textures/boqu/midtrim_blue_glow.tga
rm textures/boqu/simpledark_norm.tga
rm textures/boqu/light2_gloss.tga
rm textures/boqu/grytrimtop2_gloss.tga
rm textures/boqu/lamppanel3_norm.tga
rm textures/boqu/greytrim2x_gloss.tga
rm textures/boqu/panel_light.tga
rm textures/boqu/yellow_trim6_gloss.tga
rm textures/boqu/techtile1.tga
rm textures/boqu/ceilinglamp1.tga
rm textures/boqu/prop.tga
rm textures/boqu/factorytrim_gloss.tga
rm textures/boqu/midtrim.tga
rm textures/boqu/med_concrete.tga
rm textures/boqu/warsow_neon_gold.tga
rm textures/boqu/light_concrete1_norm.tga
rm textures/boqu/whitelight.tga
rm textures/boqu/wallbottom_norm.tga
rm textures/boqu/rect_lamp_yellow_glow.tga
rm textures/boqu/metal_brushed_gloss.tga
rm textures/boqu/rect_lamp_norm.tga
rm textures/boqu/greytrim_norm.tga
rm textures/boqu/bright_metal.tga
rm textures/boqu/tile_slim_yellow6.tga
rm textures/boqu/yellow_trim6.tga
rm textures/boqu/fusebox_gloss.tga
rm textures/boqu/yellowpillar4_norm.tga
rm textures/boqu/midtrim_norm.tga
rm textures/boqu/midtrim_gloss.tga
rm textures/boqu/hexa_lamp.tga
rm textures/boqu/squarelamp_blue_glow.tga
rm textures/boqu/light_concrete2_Normal.tga
rm textures/boqu/lightstripe_gloss.tga
rm textures/boqu/med_con.tga
rm textures/boqu/ceilinglamptrim_yellow.tga
rm textures/boqu/light2_glow.tga
rm textures/boqu/factorytrim_norm.tga
rm textures/boqu/squarelamp.tga
rm textures/boqu/ceilinglamptrim_glow.tga
rm textures/boqu/greytrim7.tga
rm textures/boqu/yellow_pillar3_norm.tga
rm textures/boqu/light1_glow.tga
rm textures/boqu/squarelamp_gloss.tga
rm textures/boqu/prop_norm.tga
rm textures/boqu/hexagon_floor3.tga
rm textures/boqu/fusebox_2norm2.tga
rm textures/boqu/fusebox.tga
rm textures/boqu/metalpanel3_norm.tga
rm textures/boqu/greytiles_gloss.tga
rm textures/boqu/ceilinglamptrim_blue.tga
rm textures/boqu/greytrim_hexyellow.tga
rm textures/boqu/light1_gloss.tga
rm textures/boqu/hexx.tga
rm textures/boqu/hex_grate.tga
rm textures/boqu/darkgrey_hexpattern.tga
rm textures/boqu/tile_whiteglow_glow.tga
rm textures/boqu/greytrim_gloss.tga
rm textures/boqu/ceilinglamptrim_yellow_glow.tga
rm textures/boqu/tile_slim_yellow8.tga
rm textures/boqu/simpledark2.tga
rm textures/boqu/whitedoublepanel_norm.tga
rm textures/boqu/roundlighttile_norm.tga
rm textures/boqu/roundlighttile_glow.tga
rm textures/boqu/teleporterback_glow.tga
rm textures/boqu/yellowtrim_gloss.tga
rm textures/boqu/ceilinglamp_w_gloss.tga
rm textures/boqu/simplestripe_gloss.tga
rm textures/boqu/tile_slim_yellow7.tga
rm textures/boqu/stairtop_norm.tga
rm textures/boqu/gratepanel_gloss.tga
rm textures/boqu/techtile1_gloss.tga
rm textures/boqu/greytrim7_norm.tga
rm textures/boqu/wallbottom_gloss.tga
rm textures/boqu/hex_grate_norm.tga
rm textures/boqu/floorpanels_yellowstrip_gloss.tga
rm textures/boqu/hexagon_floor2_norm.tga
rm textures/boqu/wallbase2.tga
rm textures/boqu/wallbottom2.tga
rm textures/boqu/teleporterback_norm.tga
rm textures/boqu/ceilinglamp_w_norm.tga
rm textures/boqu/g256_grey.tga
rm textures/boqu/lightstripe_glow.tga
rm textures/boqu/simplestripe_norm.tga
rm textures/boqu/simplemid_grate.tga
rm textures/boqu/teleporterback_gloss.tga
rm textures/boqu/hex_grate_xnorm.tga
rm textures/boqu/stairtop.tga
rm textures/boqu/simplelight_grate.tga
rm textures/boqu/tile.tga
rm textures/boqu/floorslim_plate_norm.tga
rm textures/boqu/whitepanel2.tga
rm textures/boqu/wallbottom.tga
rm textures/boqu/door_norm.tga
rm textures/boqu/metal_brushed.ktx
rm textures/boqu/ceilinglamptrim_pink_glow.tga
rm textures/boqu/ceilinglamptrim_blue_glow.tga
rm textures/boqu/yellow_pillar3.tga
rm textures/boqu/panel.tga
rm textures/boqu/models/cctv_norm.tga
rm textures/boqu/models/doubleneon.tga
rm textures/boqu/models/modpillar1_norm.tga
rm textures/boqu/models/walllamp1_glow.tga
rm textures/boqu/models/doubleneon_norm.tga
rm textures/boqu/models/stair1.tga
rm textures/boqu/models/cctv.tga
rm textures/boqu/models/modpillar1.tga
rm textures/boqu/models/walllamp1_gloss.tga
rm textures/boqu/models/walllamp1.tga
rm textures/boqu/models/stair1_gloss.tga
rm textures/boqu/models/floortrim1_gloss.tga
rm textures/boqu/models/stair1_glow.tga
rm textures/boqu/models/doubleneon_glow.tga
rm textures/boqu/models/stair1_norm.tga
rm textures/boqu/models/floortrim1_norm.tga
rm textures/boqu/models/cctvholder_gloss.tga
rm textures/boqu/models/floortrim1.tga
rm textures/boqu/models/modpillar1_gloss.tga
rm textures/boqu/models/cctv_gloss.tga
rm textures/boqu/models/cctvholder.tga
rm textures/boqu/models/doubleneon_gloss.tga
rm textures/boqu/glow_halo_blue.tga
rm textures/boqu/bright_metalhex_norm.tga
rm textures/boqu/metalpanel3.tga
rm textures/boqu/grytrimtop2.tga
rm textures/boqu/whitepanels4.tga
rm textures/boqu/bigwhitetiles2.ktx
rm textures/boqu/gratetrim.tga
rm textures/boqu/vent.tga
rm textures/boqu/biglightfloor_gloss.tga
rm textures/boqu/cables_norm.tga
rm textures/boqu/greytrim_yellow_gloss.tga
rm textures/boqu/simpledark.tga
rm textures/boqu/stairfront_norm.tga
rm textures/boqu/whitepanel3.tga
rm textures/boqu/wallbottom2_gloss.tga
rm textures/boqu/whitepanel5_gloss.tga
rm textures/boqu/greytrim_blank_norm.tga
rm textures/boqu/treadplate_gloss.tga
rm textures/boqu/prop_glow.tga
rm textures/boqu/bigtiles.tga
rm textures/boqu/rect_lamp_yellow.ktx
rm textures/boqu/metalpanel4_norm.tga
rm textures/boqu/hexagon_floor_norm.tga
rm textures/window/purple01_gloss.tga
rm textures/window/window_dirty.tga
rm textures/window/window01_norm.tga
rm textures/window/purple01_norm.tga
rm textures/window/window_industrial.tga
rm textures/window/window01.tga
rm textures/window/windows_lit_1.tga
rm textures/window/window_dirty_gloss.tga
rm textures/window/window_industrial_norm.tga
rm textures/window/window_dirty_norm.tga
# textures/window/purple01.tga
rm textures/window/window_industrial_gloss.tga
rm textures/wdm7/blx_crocinus_pillar2_gloss.jpg
rm textures/wdm7/cx_ecel_bounce.tga
rm textures/wdm7/blx_crocinus_pillar2_norm.tga
rm textures/wdm7/oil.tga
rm textures/wdm7/grid_tile.jpg
rm textures/wdm7/blx_crocinus_pillar2.tga
rm textures/wdm7/cx_ecel_bounce_blend.tga
rm textures/wdm7/cx_ecel_bounce_small.jpg
# textures/wdm7/light_tile.tga
rm textures/36_colours/A8A8A8.tga
rm textures/36_colours/7A7A7A.tga
rm textures/36_colours/545454.tga
rm textures/36_colours/FFFFFF.tga
rm textures/36_colours/A8A8A8_gloss.tga
