rm env/stormydays/stormydays_ft.tga
rm env/stormydays/stormydays_bk.tga
rm env/stormydays/stormydays_dn.tga
rm env/stormydays/stormydays_rt.tga
rm env/stormydays/stormydays_up.tga
rm env/stormydays/stormydays_lf.tga
rm env/alleyskybox/grimmnight_ft.tga
rm env/alleyskybox/grimmnight_up.tga
rm env/alleyskybox/grimmnight_rt.tga
rm env/alleyskybox/grimmnight_bk.tga
rm env/alleyskybox/grimmnight_dn.tga
rm env/alleyskybox/grimmnight_lf.tga
rm textures/terrain/rocks005_512x512_norm.tga
rm textures/terrain/rocks002_512x512_norm.tga
rm textures/terrain/sand_dark.tga
rm textures/terrain/sand_dark_norm.tga
rm textures/terrain/rockwall01.ktx
rm textures/terrain/rocks006_512x512.ktx
rm textures/terrain/soilsand0104.ktx
rm textures/terrain/rocks001_512x512.ktx
rm textures/terrain/sand_norm.tga
rm textures/terrain/rocks001_512x512_norm.tga
rm textures/terrain/rocks006_512x512_norm.tga
rm textures/terrain/soilsand0104_norm.tga
rm textures/terrain/rocks002_512x512.ktx
rm textures/terrain/sand.ktx
rm textures/terrain/rocks005_512x512.ktx
rm textures/terrain/rockwall01_norm.tga
rm textures/metal/metalrust_iron6_gloss.tga
rm textures/metal/metalrust_iron6.ktx
rm textures/metal/corrugated0023green_gloss.tga
rm textures/metal/corrugated0023.ktx
rm textures/metal/corrugated0023_norm.tga
rm textures/metal/corrugated0023green.ktx
rm textures/metal/corrugated0023_gloss.tga
rm textures/metal/corrugated0023oxid.ktx
rm textures/metal/metalrust_iron6_norm.tga
rm textures/world/sh/lava1.tga
rm textures/world/sh/water1.tga
rm textures/world/sh/teleenergy.tga
rm textures/world/sh/lava2.tga
rm textures/world/sh/telefog.tga
rm textures/world/sh/slime1.tga
rm textures/world/sh/telescrollup2.tga
rm textures/world/sh/lava1_glow.tga
rm textures/world/sh/slime2.tga
rm textures/world/sh/telescrollup1.tga
rm textures/world/sh/water2.tga
rm textures/world/sh/pooltint.tga
rm textures/world/water/water5_dudv.tga
rm textures/world/water/wat_norm3.jpg
rm textures/world/water/wat_norm2.jpg
rm textures/world/water/water5_norm.tga
rm textures/world/water/wat_gloss.jpg
rm textures/world/water/norm.jpg
rm textures/world/water/wat_dudv.tga
rm textures/noir/concrete1.tga
rm textures/noir/seka_norm.tga
rm textures/noir/seka.tga
rm textures/noir/door2.tga
rm textures/noir/concrete1_norm.tga
rm textures/noir/brickgrey_norm.tga
rm textures/noir/door2_norm.tga
rm textures/noir/door2m_norm.tga
rm textures/noir/door2m.tga
rm textures/noir/brickgrey.tga
rm textures/test/UVtest.tga
rm textures/concrete/oldplasterdetail.ktx
rm textures/concrete/oldplasterdetail_norm.tga
rm textures/concrete/oldplaster2uniform.ktx
rm textures/concrete/plaster2uniform.ktx
rm textures/concrete/roadbarrier_concrete.tga
rm textures/concrete/plasterred01_norm.tga
rm textures/concrete/roadbarrier_concrete_norm.tga
rm textures/concrete/roadbarrier_concrete_height.tga
rm textures/concrete/plasterred01.ktx
rm textures/concrete/roadbarrier_concrete_gloss.tga
rm textures/concrete/oldplaster2uniform_norm.tga
rm textures/concrete/plaster2uniform_norm.tga
rm textures/scifi_interior/bricks_orange.tga
rm textures/scifi_interior/bricks_norm.tga
rm textures/scifi_interior/bricks_gloss.tga
rm textures/scifi_interior/bricks.tga
rm textures/scifi_interior/bricks_blue.tga
rm textures/melee/50u1.tga
rm textures/melee/metal001.ktx
rm textures/melee/stone001.ktx
rm textures/melee/stone000.ktx
rm textures/melee/metal002.ktx
rm textures/melee/glass.tga
rm textures/decals/decal_drop.tga
rm textures/decals/decal_telesign_left.tga
rm textures/decals/decal_telesign_right.tga
rm textures/decals/decal_danger.tga
rm textures/decals/decal_health.tga
rm textures/decals/decal_armor_ya.tga
rm textures/decals/dirt_02.tga
rm textures/decals/dirt_scratch_01.tga
rm textures/decals/decal_dirt2.tga
rm textures/decals/dirt_01_norm.tga
rm textures/decals/dirt_02_norm.tga
rm textures/decals/decal_armor_ga.tga
rm textures/decals/decal_armor_ra.tga
rm textures/decals/dirt_scratch_02_norm.tga
rm textures/decals/dirt_01.tga
rm textures/decals/decal_dirt1.tga
rm textures/decals/dirt_scratch_02.tga
rm textures/decals/dirt_scratch_01_norm.tga
rm sounds/menu/back.wav
rm sounds/menu/mouseover.wav
rm sounds/menu/ok.wav
rm sounds/misc/chat.wav
rm sounds/misc/gibs_explosion.wav
rm sounds/misc/timer_bip_bip.wav
rm sounds/misc/timer_ploink.wav
rm video/backsequence_06.roq
rm sounds/ambient/ceilingfan.ogg
rm sounds/bomb/bombtimer.ogg
rm sounds/ctftactics/turret_pain01.wav
rm sounds/items/armor_green.ogg
rm sounds/items/armor_red.ogg
rm sounds/items/armor_shard.ogg
rm sounds/items/armor_yellow.ogg
rm sounds/items/health_25.ogg
rm sounds/items/health_5.ogg
rm sounds/items/health_50.ogg
rm sounds/items/item_idle.ogg
rm sounds/items/item_spawn.ogg
rm sounds/items/megahealth.ogg
rm sounds/items/regen_pickup.ogg
rm sounds/items/regen_spawn.ogg
rm sounds/movers/door_start.ogg
rm sounds/movers/door_start2.ogg
rm sounds/movers/door_stop.ogg
rm sounds/movers/elevator_move.ogg
rm sounds/players/bobot/dash_1.ogg
rm sounds/players/bobot/dash_2.ogg
rm sounds/players/bobot/death.ogg
rm sounds/players/bobot/drown.ogg
rm sounds/players/bobot/falldeath.ogg
rm sounds/players/bobot/fall_0.ogg
rm sounds/players/bobot/fall_1.ogg
rm sounds/players/bobot/fall_2.ogg
rm sounds/players/bobot/gasp.ogg
rm sounds/players/bobot/jump_1.ogg
rm sounds/players/bobot/jump_2.ogg
rm sounds/players/bobot/pain100.ogg
rm sounds/players/bobot/pain25.ogg
rm sounds/players/bobot/pain50.ogg
rm sounds/players/bobot/pain75.ogg
rm sounds/players/bobot/wj_1.ogg
rm sounds/players/bobot/wj_2.ogg
rm sounds/players/male/dash_1.ogg
rm sounds/players/male/dash_2.ogg
rm sounds/players/male/death.ogg
rm sounds/players/male/drown.ogg
rm sounds/players/male/falldeath.ogg
rm sounds/players/male/fall_0.ogg
rm sounds/players/male/fall_1.ogg
rm sounds/players/male/fall_2.ogg
rm sounds/players/male/gasp.ogg
rm sounds/players/male/jump_1.ogg
rm sounds/players/male/jump_2.ogg
rm sounds/players/male/pain100.ogg
rm sounds/players/male/pain25.ogg
rm sounds/players/male/pain50.ogg
rm sounds/players/male/pain75.ogg
rm sounds/players/male/wj_1.ogg
rm sounds/players/male/wj_2.ogg
rm sounds/weapons/bladegun_strong_fire.ogg
rm sounds/weapons/bladegun_strong_hit_1.ogg
rm sounds/weapons/bladegun_strong_hit_2.ogg
rm sounds/weapons/bladegun_strong_hit_3.ogg
rm sounds/weapons/blade_hitflsh1.ogg
rm sounds/weapons/blade_hitflsh2.ogg
rm sounds/weapons/blade_hitflsh3.ogg
rm sounds/weapons/blade_hitwall1.ogg
rm sounds/weapons/blade_hitwall2.ogg
rm sounds/weapons/blade_strike1.ogg
rm sounds/weapons/blade_strike2.ogg
rm sounds/weapons/blade_strike3.ogg
rm sounds/weapons/electrobolt_hit.ogg
rm sounds/weapons/electrobolt_hum.ogg
rm sounds/weapons/gren_strong_explosion1.ogg
rm sounds/weapons/gren_strong_explosion2.ogg
rm sounds/weapons/laser_hit0.ogg
rm sounds/weapons/laser_hit1.ogg
rm sounds/weapons/laser_hit2.ogg
rm sounds/weapons/plasmagun_strong_explosion.ogg
rm sounds/weapons/ric1.ogg
rm sounds/weapons/ric2.ogg
rm sounds/weapons/riotgun_strong_hit.ogg
rm sounds/weapons/rocket_fire_strong.ogg
rm sounds/weapons/rocket_fly_strong.ogg
rm sounds/weapons/rocket_strong_explosion.ogg
rm sounds/weapons/weapon_switch.ogg
rm sounds/world/dong.wav
rm sounds/world/ft_step1.ogg
rm sounds/world/ft_step2.ogg
rm sounds/world/ft_step3.ogg
rm sounds/world/ft_step_met1.ogg
rm sounds/world/ft_step_met2.ogg
rm sounds/world/ft_step_met3.ogg
rm sounds/world/ft_walljump_failed.ogg
rm sounds/world/jumppad.ogg
rm sounds/world/launchpad.ogg
rm sounds/world/lava_in.ogg
rm sounds/world/lava_out.ogg
rm sounds/world/player_respawn.ogg
rm sounds/world/tele_in.ogg
rm sounds/world/underlava.ogg
rm sounds/world/underwater.ogg
