#ifndef __NOESIS_PCH_H__
#define __NOESIS_PCH_H__


// Core/Kernel
#include <NsCore/Type.h>
#include <NsCore/AssignableFromType.h>
#include <NsCore/Error.h>
#include <NsCore/MemoryStream.h>
#include <NsCore/Delegate.h>
#include <NsCore/TypeEnumImpl.h>
#include <NsCore/TypeId.h>
#include <NsCore/StringFormat.h>
#include <NsCore/TypeEnum.h>
#include <NsCore/TypeClass.h>
#include <NsCore/Version.h>
#include <NsCore/RegisterComponent.h>
#include <NsCore/KernelApi.h>
#include <NsCore/TypeEnumHelper.h>
#include <NsCore/ReflectionImplementEmpty.h>
#include <NsCore/BaseObject.h>
#include <NsCore/Symbol.h>
#include <NsCore/TypePropertyImpl.h>
#include <NsCore/TypeMetaData.h>
#include <NsCore/Boxing.h>
#include <NsCore/Find.h>
#include <NsCore/BaseComponent.h>
#include <NsCore/StringUtils.h>
#include <NsCore/TypePropertyUtil.h>
#include <NsCore/File.h>
#include <NsCore/NsFactory.h>
#include <NsCore/TypeOf.h>
#include <NsCore/TypePointer.h>
#include <NsCore/Stream.h>
#include <NsCore/TypeOfBasic.h>
#include <NsCore/Noesis.h>
#include <NsCore/MetaData.h>
#include <NsCore/FixedAllocator.h>
#include <NsCore/TypeProperty.h>
#include <NsCore/Interface.h>
#include <NsCore/Package.h>
#include <NsCore/ReflectionDeclareEnum.h>
#include <NsCore/DynamicCast.h>
#include <NsCore/ComponentFactory.h>
#include <NsCore/ReflectionHelper.h>
#include <NsCore/Log.h>
#include <NsCore/FileStream.h>
#include <NsCore/TypeClassCreator.h>
#include <NsCore/PlatformSettings.h>
#include <NsCore/CompilerSettings.h>
#include <NsCore/HighResTimer.h>
#include <NsCore/Kernel.h>
#include <NsCore/Category.h>
#include <NsCore/ReflectionImplementEnum.h>
#include <NsCore/Memory.h>
#include <NsCore/TypeEnumCreator.h>
#include <NsCore/BaseRefCounted.h>
#include <NsCore/CpuProfiler.h>
#include <NsCore/TypeCollection.h>
#include <NsCore/Ptr.h>
#include <NsCore/CompilerTools.h>
#include <NsCore/TypeClassCreatorEmpty.h>
#include <NsCore/TypeOfBase.h>
#include <NsCore/TypeMeta.h>
#include <NsCore/IdOf.h>
#include <NsCore/ReflectionImplement.h>
#include <NsCore/MemProfiler.h>
#include <NsCore/Hash.h>
#include <NsCore/TypeClassBuilder.h>
#include <NsCore/UTF8.h>
#include <NsCore/TypeInfo.h>
#include <NsCore/ReflectionDeclare.h>
#include <NsCore/TypeCreate.h>
#include <NsCore/ReflectionRegistry.h>
#include <NsCore/TypeOfForward.h>
#include <NsCore/TypeOfPointer.h>
#include <NsCore/ValueHelper.h>
#include <NsCore/Atomic.h>

// Core/Nullable
#include <NsCore/Nullable.h>
#include <NsCore/NullableApi.h>

// Core/NSTL
#include <NsCore/NSTLForwards.h>
#include <NsCore/Bitset.h>
#include <NsCore/NSTLPoolAllocator.h>
#include <NsCore/Map.h>
#include <NsCore/HashMap.h>
#include <NsCore/List.h>
#include <NsCore/HashSet.h>
#include <NsCore/Deque.h>
#include <NsCore/Stack.h>
#include <NsCore/FixedVector.h>
#include <NsCore/Vector.h>
#include <NsCore/FixedString.h>
#include <NsCore/Queue.h>
#include <NsCore/Set.h>
#include <NsCore/String.h>

// Math/Utils
#include <NsMath/Utils.h>
#include <NsMath/Constants.h>

// Core/TypeConverter
#include <NsCore/NullableConverter.h>
#include <NsCore/EnumConverter.h>
#include <NsCore/Converter.h>
#include <NsCore/StringConverter.h>
#include <NsCore/NumericConverter.h>
#include <NsCore/TypeConverter.h>
#include <NsCore/CharConverter.h>
#include <NsCore/TypeConverterApi.h>
#include <NsCore/SymbolConverter.h>

// Math/VectorMath
#include <NsMath/VectorMathApi.h>
#include <NsMath/AABoxForward.h>
#include <NsMath/MatrixForward.h>
#include <NsMath/TransformForward.h>
#include <NsMath/Matrix.h>
#include <NsMath/AABBox.h>
#include <NsMath/VectorForward.h>
#include <NsMath/Transform.h>
#include <NsMath/Vector.h>

// Gui/DependencySystem
#include <NsGui/ValueStorageManagerImpl.h>
#include <NsGui/IComponentInitializer.h>
#include <NsGui/DispatcherObject.h>
#include <NsGui/DependencySystemApi.h>
#include <NsGui/TypeConverterMetaData.h>
#include <NsGui/DependencyProperty.h>
#include <NsGui/ValueDestination.h>
#include <NsGui/FreezableEventReason.h>
#include <NsGui/INotifyPropertyChanged.h>
#include <NsGui/Freezable.h>
#include <NsGui/ProviderValue.h>
#include <NsGui/DependencyObjectValueData.h>
#include <NsGui/Expression.h>
#include <NsGui/DependencyData.h>
#include <NsGui/ChangedHandler.h>
#include <NsGui/PropertyMetadata.h>
#include <NsGui/ISealable.h>
#include <NsGui/DependencyObject.h>
#include <NsGui/ValueStorageManager.h>
#include <NsGui/ContentPropertyMetaData.h>

// Drawing/Types
#include <NsDrawing/Size.h>
#include <NsDrawing/TypesApi.h>
#include <NsDrawing/Point.h>
#include <NsDrawing/Color.h>
#include <NsDrawing/Thickness.h>
#include <NsDrawing/CornerRadius.h>
#include <NsDrawing/Rect.h>
#include <NsDrawing/SVGPath.h>

// Render/RenderDevice
#include <NsRender/RenderDeviceApi.h>
#include <NsRender/RenderDevice.h>
#include <NsRender/Texture.h>
#include <NsRender/RenderTarget.h>

// Gui/Core
#include <NsGui/ControlTemplate.h>
#include <NsGui/TickBar.h>
#include <NsGui/StatusBarItem.h>
#include <NsGui/INameScopeTypes.h>
#include <NsGui/CompositionUnderline.h>
#include <NsGui/RectangleGeometry.h>
#include <NsGui/ToolBarPanel.h>
#include <NsGui/EllipseGeometry.h>
#include <NsGui/GradientStopCollection.h>
#include <NsGui/IView.h>
#include <NsGui/ListBoxItem.h>
#include <NsGui/UIElement.h>
#include <NsGui/BindingListener.h>
#include <NsGui/Selector.h>
#include <NsGui/MultiDataTrigger.h>
#include <NsGui/MeshGeometry.h>
#include <NsGui/KeyboardNavigation.h>
#include <NsGui/IValueConverter.h>
#include <NsGui/ICollectionView.h>
#include <NsGui/IItemContainerGenerator.h>
#include <NsGui/TemplateBindingExtension.h>
#include <NsGui/Page.h>
#include <NsGui/GeometryGroup.h>
#include <NsGui/ProgressBar.h>
#include <NsGui/ResourceDictionary.h>
#include <NsGui/RoutedCommand.h>
#include <NsGui/UniformGrid.h>
#include <NsGui/Control.h>
#include <NsGui/TextBox.h>
#include <NsGui/BaseValueConverter.h>
#include <NsGui/INotifyDictionaryChanged.h>
#include <NsGui/Label.h>
#include <NsGui/BitmapSource.h>
#include <NsGui/TriggerAction.h>
#include <NsGui/NameScopePropertyMetaData.h>
#include <NsGui/CompositeTransform.h>
#include <NsGui/VirtualizingPanel.h>
#include <NsGui/BaseUICollection.h>
#include <NsGui/StackPanel.h>
#include <NsGui/DataTrigger.h>
#include <NsGui/ToolBarTray.h>
#include <NsGui/Bold.h>
#include <NsGui/Popup.h>
#include <NsGui/Text.h>
#include <NsGui/Projection.h>
#include <NsGui/ToggleButton.h>
#include <NsGui/HeaderedItemsControl.h>
#include <NsGui/ApplicationCommands.h>
#include <NsGui/ItemContainerGenerator.h>
#include <NsGui/UpdateSourceTrigger.h>
#include <NsGui/BaseDefinition.h>
#include <NsGui/Condition.h>
#include <NsGui/FrameworkPropertyMetadata.h>
#include <NsGui/TranslateTransform.h>
#include <NsGui/Style.h>
#include <NsGui/RenderOptions.h>
#include <NsGui/GroupBox.h>
#include <NsGui/FontFamily.h>
#include <NsGui/CollectionView.h>
#include <NsGui/SolidColorBrush.h>
#include <NsGui/ComponentCommands.h>
#include <NsGui/BaseButton.h>
#include <NsGui/ContentPresenter.h>
#include <NsGui/Path.h>
#include <NsGui/IUITreeNodeTypes.h>
#include <NsGui/BaseSetter.h>
#include <NsGui/CommandBinding.h>
#include <NsGui/ComboBox.h>
#include <NsGui/FocusManager.h>
#include <NsGui/FormattedText.h>
#include <NsGui/VirtualizationCacheLength.h>
#include <NsGui/TextBlock.h>
#include <NsGui/BulletDecorator.h>
#include <NsGui/Uri.h>
#include <NsGui/Italic.h>
#include <NsGui/BitmapImage.h>
#include <NsGui/Trigger.h>
#include <NsGui/ObservableCollection.h>
#include <NsGui/IUITreeNode.h>
#include <NsGui/ListBox.h>
#include <NsGui/Pen.h>
#include <NsGui/MatrixTransform.h>
#include <NsGui/BaseBinding.h>
#include <NsGui/HeaderedContentControl.h>
#include <NsGui/StreamGeometryContext.h>
#include <NsGui/TemplatePartMetaData.h>
#include <NsGui/CombinedGeometry.h>
#include <NsGui/VisualTreeHelper.h>
#include <NsGui/TextElement.h>
#include <NsGui/StatusBar.h>
#include <NsGui/ColumnDefinition.h>
#include <NsGui/CommandData.h>
#include <NsGui/Matrix3DProjection.h>
#include <NsGui/VirtualizingStackPanel.h>
#include <NsGui/KeyBinding.h>
#include <NsGui/ImageSource.h>
#include <NsGui/InputEnums.h>
#include <NsGui/FrameworkTemplate.h>
#include <NsGui/ResourceKeyType.h>
#include <NsGui/LogicalTreeHelper.h>
#include <NsGui/Events.h>
#include <NsGui/IRenderer.h>
#include <NsGui/ContextMenu.h>
#include <NsGui/InlineUIContainer.h>
#include <NsGui/ValueTargetProvider.h>
#include <NsGui/Animatable.h>
#include <NsGui/UIElementEvents.h>
#include <NsGui/DataObject.h>
#include <NsGui/BaseCommand.h>
#include <NsGui/SizeChangedInfo.h>
#include <NsGui/DependsOnAttributeMetaData.h>
#include <NsGui/ContentControl.h>
#include <NsGui/ImageBrush.h>
#include <NsGui/BindingOperations.h>
#include <NsGui/KeyGesture.h>
#include <NsGui/Thumb.h>
#include <NsGui/ILayerManager.h>
#include <NsGui/ContextMenuService.h>
#include <NsGui/UIElementCollection.h>
#include <NsGui/IListIndexer.h>
#include <NsGui/Visual.h>
#include <NsGui/Colors.h>
#include <NsGui/BaseMenu.h>
#include <NsGui/ItemsPresenter.h>
#include <NsGui/Inline.h>
#include <NsGui/Shape.h>
#include <NsGui/ScaleTransform.h>
#include <NsGui/PlaneProjection.h>
#include <NsGui/IDictionary.h>
#include <NsGui/TabControl.h>
#include <NsGui/PropertyPath.h>
#include <NsGui/IRecyclingItemContainerGenerator.h>
#include <NsGui/TreeViewItem.h>
#include <NsGui/IScrollInfo.h>
#include <NsGui/Grid.h>
#include <NsGui/CollectionViewSource.h>
#include <NsGui/IRenderProxyCreator.h>
#include <NsGui/LinearGradientBrush.h>
#include <NsGui/Brushes.h>
#include <NsGui/IResourceKey.h>
#include <NsGui/CheckBox.h>
#include <NsGui/BaseFreezableCollection.h>
#include <NsGui/FrameworkElementEvents.h>
#include <NsGui/Mouse.h>
#include <NsGui/Enums.h>
#include <NsGui/ResourceKeyString.h>
#include <NsGui/ScrollContentPresenter.h>
#include <NsGui/UICollection.h>
#include <NsGui/StreamGeometry.h>
#include <NsGui/ScrollBar.h>
#include <NsGui/VisualCollection.h>
#include <NsGui/InputBinding.h>
#include <NsGui/Track.h>
#include <NsGui/BaseDictionary.h>
#include <NsGui/BaseTextBox.h>
#include <NsGui/IDictionaryIndexer.h>
#include <NsGui/Slider.h>
#include <NsGui/DrawingContext.h>
#include <NsGui/ItemCollection.h>
#include <NsGui/ItemsPanelTemplate.h>
#include <NsGui/FreezableCollection.h>
#include <NsGui/Element.h>
#include <NsGui/HierarchicalDataTemplate.h>
#include <NsGui/TabItem.h>
#include <NsGui/DataTemplateSelector.h>
#include <NsGui/RowDefinition.h>
#include <NsGui/HandoffBehavior.h>
#include <NsGui/Panel.h>
#include <NsGui/TemplateBindingExpression.h>
#include <NsGui/FrameworkElement.h>
#include <NsGui/EventTrigger.h>
#include <NsGui/TileBrush.h>
#include <NsGui/Keyboard.h>
#include <NsGui/GradientBrush.h>
#include <NsGui/NameScope.h>
#include <NsGui/BaseBindingExpression.h>
#include <NsGui/ScrollViewer.h>
#include <NsGui/Separator.h>
#include <NsGui/LayerManager.h>
#include <NsGui/BaseObservableCollection.h>
#include <NsGui/Button.h>
#include <NsGui/Menu.h>
#include <NsGui/Transform.h>
#include <NsGui/Setter.h>
#include <NsGui/Viewbox.h>
#include <NsGui/Expander.h>
#include <NsGui/IntegrationAPI.h>
#include <NsGui/WrapPanel.h>
#include <NsGui/DragDrop.h>
#include <NsGui/Hyperlink.h>
#include <NsGui/InputGesture.h>
#include <NsGui/ITimeManager.h>
#include <NsGui/UIElementData.h>
#include <NsGui/RadialGradientBrush.h>
#include <NsGui/UIPropertyMetadata.h>
#include <NsGui/IPropertyValueConverter.h>
#include <NsGui/ComboBoxItem.h>
#include <NsGui/TreeView.h>
#include <NsGui/TabPanel.h>
#include <NsGui/Decorator.h>
#include <NsGui/BaseCollection.h>
#include <NsGui/ToolTipService.h>
#include <NsGui/Line.h>
#include <NsGui/Span.h>
#include <NsGui/RoutedEvent.h>
#include <NsGui/VisualBrush.h>
#include <NsGui/ToolBar.h>
#include <NsGui/ItemsControl.h>
#include <NsGui/Ellipse.h>
#include <NsGui/UserControl.h>
#include <NsGui/BindingExpression.h>
#include <NsGui/Run.h>
#include <NsGui/Rectangle.h>
#include <NsGui/INotifyCollectionChanged.h>
#include <NsGui/RepeatButton.h>
#include <NsGui/Collection.h>
#include <NsGui/RoutedUICommand.h>
#include <NsGui/CommandManager.h>
#include <NsGui/Canvas.h>
#include <NsGui/ICommandSource.h>
#include <NsGui/IStoryboard.h>
#include <NsGui/AdornerDecorator.h>
#include <NsGui/ToolTip.h>
#include <NsGui/MultiTrigger.h>
#include <NsGui/Binding.h>
#include <NsGui/DockPanel.h>
#include <NsGui/BaseTrigger.h>
#include <NsGui/SkewTransform.h>
#include <NsGui/CoreApi.h>
#include <NsGui/GradientStop.h>
#include <NsGui/RangeBase.h>
#include <NsGui/ToolBarOverflowPanel.h>
#include <NsGui/RotateTransform.h>
#include <NsGui/Brush.h>
#include <NsGui/ICommand.h>
#include <NsGui/MarkupExtension.h>
#include <NsGui/TextureSource.h>
#include <NsGui/GridLength.h>
#include <NsGui/DashStyle.h>
#include <NsGui/RelativeSource.h>
#include <NsGui/INameScope.h>
#include <NsGui/Image.h>
#include <NsGui/TransformGroup.h>
#include <NsGui/LineBreak.h>
#include <NsGui/LineGeometry.h>
#include <NsGui/MenuItem.h>
#include <NsGui/mscorlibTypes.h>
#include <NsGui/Border.h>
#include <NsGui/IList.h>
#include <NsGui/Geometry.h>
#include <NsGui/RadioButton.h>
#include <NsGui/PasswordBox.h>
#include <NsGui/DataTemplate.h>
#include <NsGui/Underline.h>

// Gui/Providers
#include <NsGui/FontProvider.h>
#include <NsGui/XamlProvider.h>
#include <NsGui/TextureProvider.h>
#include <NsGui/FontProperties.h>
#include <NsGui/TextProperties.h>

// Gui/CachedFontProvider
#include <NsGui/CachedFontProviderApi.h>
#include <NsGui/CachedFontProvider.h>

// Gui/Controls
#include <NsGui/GridViewColumnHeader.h>
#include <NsGui/ListViewItem.h>
#include <NsGui/GridViewColumn.h>
#include <NsGui/ControlsApi.h>
#include <NsGui/GridViewRowPresenter.h>
#include <NsGui/ListView.h>
#include <NsGui/BaseGridViewRowPresenter.h>
#include <NsGui/GridView.h>
#include <NsGui/BaseView.h>
#include <NsGui/GridViewHeaderRowPresenter.h>

// Gui/Animation
#include <NsGui/PauseStoryboard.h>
#include <NsGui/VisualTransition.h>
#include <NsGui/IEasingFunction.h>
#include <NsGui/ClockGroup.h>
#include <NsGui/AnimationApi.h>
#include <NsGui/Animation.h>
#include <NsGui/StopStoryboard.h>
#include <NsGui/QuadraticEase.h>
#include <NsGui/ControllableStoryboardAction.h>
#include <NsGui/KeyFrame.h>
#include <NsGui/Duration.h>
#include <NsGui/TimelineGroup.h>
#include <NsGui/CircleEase.h>
#include <NsGui/QuinticEase.h>
#include <NsGui/VisualStateGroup.h>
#include <NsGui/Storyboard.h>
#include <NsGui/VisualStateManager.h>
#include <NsGui/QuarticEase.h>
#include <NsGui/DiscreteKeyFrame.h>
#include <NsGui/BeginStoryboard.h>
#include <NsGui/AnimationUsingKeyFrames.h>
#include <NsGui/AnimationTimeline.h>
#include <NsGui/SineEase.h>
#include <NsGui/EasingFunctionBase.h>
#include <NsGui/BaseAnimation.h>
#include <NsGui/ParallelTimeline.h>
#include <NsGui/RepeatBehavior.h>
#include <NsGui/ResumeStoryboard.h>
#include <NsGui/BounceEase.h>
#include <NsGui/AnimationClock.h>
#include <NsGui/BackEase.h>
#include <NsGui/KeySpline.h>
#include <NsGui/EasingKeyFrame.h>
#include <NsGui/PowerEase.h>
#include <NsGui/Timeline.h>
#include <NsGui/SplineKeyFrame.h>
#include <NsGui/Clock.h>
#include <NsGui/TimeSpan.h>
#include <NsGui/CubicEase.h>
#include <NsGui/KeyTime.h>
#include <NsGui/LinearKeyFrame.h>
#include <NsGui/VisualState.h>
#include <NsGui/ExponentialEase.h>
#include <NsGui/ElasticEase.h>

#endif
